// Master data — Chalmond Trip: Tokyo · Sapporo · Seoul
// $100/day budget · Seafood removed · New categories: karaoke, cocktail bars,
// desserts, onsen, arcades, soup curry, tonkatsu, yakitori,
// craft beer, milmyeon, dwaeji gukbap, street food

const TRIP_DATA = {
  meta: {
    travelers: ["Forrest", "Charlotte"],
    arrive: "2026-07-25 14:00 NRT",
    return_by: "2026-08-05 Boston",
    nights: 7,
    budget_baseline_per_day: 100,
    cap_per_experience: 300,
    fx_note: "Prices in USD; JPY ~150/USD, KRW ~1370/USD"
  },
  transit: [
    {id:"t1",from:"Tokyo (NRT/HND)",to:"Sapporo (CTS)",mode:"flight",price_low:80,price_high:180,duration:"~1h35m",notes:"Peach/Jetstar/AirDo from NRT. Book 4+ weeks ahead for $80-100."},
    {id:"t2",from:"Sapporo (CTS)",to:"Seoul (ICN)",mode:"flight",price_low:180,price_high:300,duration:"~3h",notes:"Korean Air or Jeju Air. Tuesday mornings tend to be cheapest."},
    {id:"t4",from:"Seoul (ICN)",to:"Boston (BOS)",mode:"flight",price_low:700,price_high:1100,duration:"15-20h with connections",notes:"Direct on Korean Air (~14h) or one connection via NRT."}
  ],
  cities: {
    tokyo: {
      name:"Tokyo", nights:2, dates:"Jul 25-27",
      hero_lat:35.6595, hero_lng:139.7005,
      categories: {
        lodging: [
          {id:"tok-l1",name:"The Millennials Shibuya",lat:35.6621944,lng:139.6997456,rating:4.4,price_low:55,price_high:90,blurb:"Sleek capsule in the heart of Shibuya. Double-bed pods with AC, blackout blinds. Daily happy hour. Five-minute walk to the scramble.",why:"Best capsule base for nightlife and food.",place_id:"ChIJceXj8aiMGGAR0uO6fPWvo9Y"},
          {id:"tok-l2",name:"9h nine hours Shinjuku",lat:35.6903539,lng:139.7082415,rating:3.5,price_low:35,price_high:55,blurb:"Minimalist design capsule. Cashless QR entry. Very clean and quiet. Women's floor here; men's branch 2 blocks away.",why:"Cheapest reliable option. Gender-segregated — worth knowing.",place_id:"ChIJj9u6ZReNGGARWf7nVDsrB8A"},
          {id:"tok-l3",name:"BOOK AND BED Shibuya",lat:35.659762,lng:139.6950684,rating:4.2,price_low:45,price_high:75,blurb:"Library-themed hostel — you sleep in the bookshelves. Excellent club proximity. More character than Millennials.",why:"Mid-tier alt if Millennials is booked.",place_id:"ChIJURcnkcKNGGAR7lxdNDt4BCA"},
          {id:"tok-l4",name:"Anshin Oyado Shinjuku (Men only)",lat:35.6892851,lng:139.7028627,rating:4.2,price_low:50,price_high:80,blurb:"Best capsule amenities: full onsen/sauna floor included, sound-absorbing pods, free breakfast coffee. Men-only facility.",why:"If Forrest books separately and wants the full onsen package.",place_id:"ChIJJ8L_6dqMGGAR-ibwhw6hN8A"}
        ],
        wagyu: [
          {id:"tok-w1",name:"WAGYUMAFIA District (Shibuya)",lat:35.6708932,lng:139.7131729,rating:4.2,price_low:40,price_high:80,blurb:"Accessible Wagyumafia entry point: wagyu sliders and the legendary katsu sandwich made to order. Industrial-cool counter.",why:"Brand experience without the $300+ omakase.",place_id:"ChIJQy4s5muNGGARxk96FodyZ2c"},
          {id:"tok-w2",name:"YAKINIKUMAFIA Ikebukuro",lat:35.7293267,lng:139.7133007,rating:4.8,price_low:80,price_high:160,blurb:"Full Wagyumafia A5 yakiniku: grill premium cuts at the table, theatrical service, staff explain every cut.",why:"The proper Wagyumafia experience.",place_id:"ChIJ0w54OyWNGGARCFZMIAzH7R8"},
          {id:"tok-w3",name:"A5 Wagyu PANGA Ueno",lat:35.7071098,lng:139.7740939,rating:4.9,price_low:60,price_high:120,blurb:"Highest-rated yakiniku in the dataset (4.9 stars / 2K+ reviews). Premium A5 cuts, English-friendly staff. Reservation required.",why:"Best user-rated wagyu; better value than Wagyumafia.",place_id:"ChIJGfV-MgOPGGARZD8WM_Q1GAs"},
          {id:"tok-w4",name:"Ginza Steak Shinjuku (unlimited A5, 70 min)",lat:35.6908987,lng:139.7024029,rating:4.8,price_low:80,price_high:130,blurb:"9-course set with 70 minutes unlimited A5 wagyu. Halal-certified. High-volume but the meat quality is legit.",why:"Most wagyu per dollar.",place_id:"ChIJ1yFmDFuNGGAROVyfi6o8TII"},
          {id:"tok-w5",name:"Kobe Beef Kaiseki 511 (Akasaka)",lat:35.674649,lng:139.735433,rating:4.5,price_low:150,price_high:250,blurb:"Multi-course Kobe beef kaiseki in private tatami rooms with a 50-year-old bonsai tree on the table. Ceremonial.",why:"Splurge option. Once-in-a-trip tier.",place_id:"ChIJz8hGbH-MGGARBYaegg4n-9U"}
        ],
        tonkatsu: [
          {id:"tok-t1",name:"Asakusa Gyukatsu",lat:35.7107673,lng:139.7959519,rating:4.8,price_low:20,price_high:35,blurb:"Beef katsu — sear rare-cooked slices yourself on a hot stone at the table. Free rice/cabbage/miso refills. About a 30-minute queue.",why:"4.8 stars; best katsu in Tokyo. Pairs with Senso-ji.",place_id:"ChIJAQBs38aOGGARoOBOR4LoBdI"},
          {id:"tok-t2",name:"Tonkatsu Maisen Aoyama",lat:35.667925,lng:139.7115365,rating:4.4,price_low:22,price_high:40,blurb:"Iconic pork tonkatsu in a converted 1920s public bathhouse. Black pork cutlet is the move. Katsu sando to take away.",why:"Tokyo institution. Best pork katsu.",place_id:"ChIJa2mnui2NGGAR7z4tvWkl7HM"},
          {id:"tok-t3",name:"Katsukura Shinjuku (Times Square 14F)",lat:35.6876313,lng:139.7021224,rating:4.5,price_low:25,price_high:45,blurb:"Premium tonkatsu on the 14th floor. Grind sesame sauce at the table. Unlimited cabbage/rice/miso included.",why:"Convenient Shinjuku location; reliable quality.",place_id:"ChIJxeqRsdqMGGARy6m80_WcWLw"}
        ],
        yakitori: [
          {id:"tok-y1",name:"Yakitori Tsukuda Shibuya",lat:35.6578124,lng:139.699061,rating:4.7,price_low:35,price_high:70,blurb:"Counter-seat yakitori omakase — watch every skewer grilled over charcoal. English-speaking staff. Ten-minute walk from Millennials.",why:"Best yakitori sit-down in Shibuya.",place_id:"ChIJcydQXa2LGGAR8w_ic_FMPhw"},
          {id:"tok-y2",name:"Hinotori Shinjuku",lat:35.6949791,lng:139.6956065,rating:4.8,price_low:30,price_high:55,blurb:"All-chicken menu: thighs, tails, hearts, lotus root, mushrooms. AYCE-drink option available. Smoky alley energy.",why:"More casual; good for a group drinking session.",place_id:"ChIJTYiuESqNGGAR09srILHl_48"}
        ],
        karaoke: [
          {id:"tok-k1",name:"Rainbow Karaoke Shibuya",lat:35.661668,lng:139.7004926,rating:4.2,price_low:15,price_high:30,blurb:"Clean private rooms, self-serve unlimited soft drinks, solid English song selection. Open until 5am.",why:"Best-reviewed Shibuya karaoke for foreigners.",place_id:"ChIJEQ92ZKiMGGARzt-fA0_nHf8"},
          {id:"tok-k2",name:"Premium Karaoke MODIS Shibuya",lat:35.6611166,lng:139.7002715,rating:4.5,price_low:25,price_high:55,blurb:"11 luxury concept rooms each with unique theme. All-you-can-drink included. Best-designed karaoke space in Tokyo.",why:"The splurge karaoke option.",place_id:"ChIJ8TgX6pCNGGARRqHCKyaM3Lw"},
          {id:"tok-k3",name:"Karaoke Pasela Shibuya",lat:35.6612974,lng:139.7010822,rating:4.3,price_low:15,price_high:35,blurb:"Multi-floor karaoke plus restaurant. Famous honey toast dessert. Open until 5-7am. All-you-can-drink option.",why:"Good if you want food alongside karaoke.",place_id:"ChIJe5MIdKiMGGARcm5DIGmTTRY"}
        ],
        cocktail_bar: [
          {id:"tok-cb1",name:"SummerFall Tap Cocktails (Shibuya)",lat:35.6629812,lng:139.6955670,rating:4.9,price_low:18,price_high:35,blurb:"20 original tap cocktails built on sake brewed in-house. Off the main drag, intimate. Hoji Negroni and Shibuya Lemon Sour are standouts.",why:"4.9 stars; best cocktails in Shibuya.",place_id:"ChIJmRwRD7-NGGARjPAHExifuZg"},
          {id:"tok-cb2",name:"LOST BAR Shibuya",lat:35.6607552,lng:139.6974298,rating:4.7,price_low:20,price_high:40,blurb:"Popular bar with gacha machines at the door, strong cocktails, cozy booths. Book ahead on weekends.",why:"Most talked-about Shibuya bar among visitors.",place_id:"ChIJh7VWYQCNGGAR4HpE2vH8gAU"},
          {id:"tok-cb3",name:"TAP and CROWLER Shibuya (craft beer)",lat:35.6629752,lng:139.6971674,rating:4.9,price_low:15,price_high:30,blurb:"18 Japanese craft beers on rotating tap. Untappd-verified list. Bar snacks available.",why:"4.9 stars; best Japanese craft beer bar in the area.",place_id:"ChIJzXYUW-yNGGAR0B8fZ-9yy_Y"}
        ],
        onsen: [
          {id:"tok-o1",name:"Thermae-Yu (Shinjuku Kabukicho, 24h)",lat:35.694526,lng:139.705139,rating:4.1,price_low:20,price_high:30,blurb:"7-floor 24h onsen spa in Shinjuku. Multiple bath types including carbonated, silky, and open-air. Sauna, cold plunge. Towels and yukata provided.",why:"Best post-club recovery and jet-lag reset in Tokyo.",place_id:"ChIJHyXsZNmMGGARHG4NYfRhgMA"}
        ],
        arcade: [
          {id:"tok-ar1",name:"GiGO Akihabara Building 3",lat:35.6992456,lng:139.7709552,rating:4.1,price_low:5,price_high:20,blurb:"6 floors of arcade. Floor 6 is a retro vault: House of the Dead 1-4, Daytona, Outrun, Street Fighter, Space Invaders. Seating and vending machines on site.",why:"Best retro gaming floor in Tokyo.",place_id:"ChIJR-PMBx2MGGARPFrgtULaJB0"},
          {id:"tok-ar2",name:"HEY (Hirose Entertainment Yard) Akihabara",lat:35.699072,lng:139.770917,rating:4.3,price_low:5,price_high:20,blurb:"Specialist retro and fighting games: Rayforce, Darius, Virtua On, Puzzle Bobble 4. Dark atmospheric setting. The serious player's arcade.",why:"Best for fighting games and shmup depth.",place_id:"ChIJlUSnDx2MGGARpBmTLzsBJV0"}
        ],
        market: [
          {id:"tok-m1",name:"Toyosu Market (viewing + stalls)",lat:35.6440911,lng:139.784281,rating:3.6,price_low:15,price_high:40,blurb:"5am tuna auction viewing gallery (arrive early). Afterward: tamagoyaki, beef curry bowls, stall breakfasts. Closed Wed and Sun. Plenty of non-seafood stalls.",why:"The auction is the spectacle regardless of what you eat.",place_id:"ChIJW4-7z_iJGGAR3DNQUg6tv9Y"},
          {id:"tok-m2",name:"Tsukiji Outer Market",lat:35.6647703,lng:139.7702515,rating:4.2,price_low:15,price_high:35,blurb:"Narrow stall-lined streets: tamagoyaki, gyoza, beef skewers, tamago sando, pickles. Closes around 1pm. Plenty of non-seafood options.",why:"More atmosphere than Toyosu; good for grazing.",place_id:"ChIJW2cLzSGLGGARXAKXv6EkbqI"}
        ],
        izakaya: [
          {id:"tok-i1",name:"Omoide Yokocho (Memory Lane)",lat:35.6927011,lng:139.6995778,rating:4.2,price_low:25,price_high:50,blurb:"Narrow lantern-lit alley by Shinjuku Station with tiny yakitori counters. Touristy but the atmosphere is earned.",why:"From your original plan; the iconic photo spot.",place_id:"ChIJP9eKBdeMGGAR0zzBXJNVj5A"},
          {id:"tok-i2",name:"KINKA Sushi Bar Izakaya (Shibuya)",lat:35.6625123,lng:139.6987412,rating:4.5,price_low:35,price_high:60,blurb:"Aburi (torch-seared) small plates, karaage, crab croquette, chicken dishes. English menu, fast service. Reservations recommended.",why:"Solid sit-down dinner near Millennials.",place_id:"ChIJz9NsIKmMGGAR6LA78zkpeGY"},
          {id:"tok-i3",name:"Kichiri Shibuya",lat:35.6598715,lng:139.6993142,rating:4.4,price_low:30,price_high:55,blurb:"Modern izakaya with a 5500 yen all-you-can-drink plus food course option. English menu. Good pre-club dinner.",why:"Pre-club dinner with unlimited drinks option.",place_id:"ChIJBwm1MaiMGGARBqX2tt2wMII"}
        ],
        ramen: [
          {id:"tok-r1",name:"Ichiran Shinjuku (24h)",lat:35.6905859,lng:139.7028052,rating:4.3,price_low:12,price_high:18,blurb:"Solo-booth tonkotsu chain. Order by vending machine, customize richness and spice, eat alone behind a curtain. Open 24 hours.",why:"24h; the must-do-once ramen experience.",place_id:"ChIJ8QwFX9qMGGARVm0p0caIeTk"},
          {id:"tok-r2",name:"Sugoi Niboshi Ramen Nagi (Golden Gai)",lat:35.6937641,lng:139.7045255,rating:4.2,price_low:14,price_high:20,blurb:"12-seat standing-only room inside Golden Gai. Punchy sardine (niboshi) broth. Unique and unlike anything else. Open 24h.",why:"Unique broth plus Golden Gai location in one stop.",place_id:"ChIJAxKeZNmMGGARQ4EOGHqSdIg"},
          {id:"tok-r3",name:"Ramen Tatsunoya Shinjuku",lat:35.6960593,lng:139.6983577,rating:4.4,price_low:14,price_high:22,blurb:"Tsukemen specialist: dip firm noodles in thick black-garlic tonkotsu broth. Ask for rice porridge finish with leftover broth.",why:"Best tsukemen in the area.",place_id:"ChIJ5f7A0SmNGGARtLzoA9hzuYk"}
        ],
        dessert: [
          {id:"tok-d1",name:"Sweet Palace Crepes (Harajuku Takeshita St)",lat:35.6711808,lng:139.7047294,rating:4.9,price_low:8,price_high:15,blurb:"4.9 star crepe stand. Crispy fresh-made crepes: strawberry/custard, matcha, banana/chocolate. Fast-moving line.",why:"Best crepes in Harajuku.",place_id:"ChIJ0dLmQgGNGGARV3LM55bTxS0"},
          {id:"tok-d2",name:"Asakusa Harajuku Matcha Crepe Bar",lat:35.6710285,lng:139.7035466,rating:4.8,price_low:10,price_high:18,blurb:"Premium loaded crepes: matcha brulee, pistachio, seasonal fillings. Dense, photogenic, café seating available.",why:"More premium sit-down crepe option.",place_id:"ChIJ6aLa_aSNGGARWS5XDCj-eLE"}
        ],
        sight: [
          {id:"tok-s1",name:"teamLab Borderless (Azabudai Hills)",lat:35.6620689,lng:139.7432671,rating:4.6,price_low:30,price_high:40,blurb:"Massive immersive digital art museum with no fixed path. Rooms bleed into each other. Book 1-2 weeks ahead.",why:"World-class. One of the best things in Tokyo.",place_id:"ChIJQ5Sa1PqJGGARUSaNKKOrMVg"},
          {id:"tok-s2",name:"Shibuya Sky",lat:35.6586719,lng:139.7019848,rating:4.6,price_low:25,price_high:35,blurb:"Open-air rooftop deck atop Shibuya Scramble Square. 360 degree views, Mt Fuji on clear days. Sunset slots sell out weeks ahead.",why:"Best skyline view in Tokyo.",place_id:"ChIJ4Rr2JWiLGGARcyRSHuZ-9G8"},
          {id:"tok-s3",name:"Senso-ji Temple (Asakusa)",lat:35.7147651,lng:139.7966553,rating:4.6,price_low:0,price_high:0,blurb:"Tokyo's oldest Buddhist temple. Walk Nakamise-dori on approach for snacks and souvenirs. Free, photogenic at any time.",why:"Free, traditional, half-day with Asakusa Gyukatsu.",place_id:"ChIJ8T1GpMGOGGARDYGSgpooDWw"}
        ],
        club: [
          {id:"tok-c1",name:"WOMB Shibuya",lat:35.6584234,lng:139.6949451,rating:3.9,price_low:25,price_high:40,blurb:"Three-floor techno institution. The Shibuya classic. Packed on weekends, smoking indoors. Bass-heavy all night.",why:"From your original plan; iconic club.",place_id:"ChIJQVW_FKqMGGARQwUFx1IqoEc"},
          {id:"tok-c2",name:"ageHa (Shinkiba)",lat:35.6422443,lng:139.8249074,rating:4.5,price_low:30,price_high:50,blurb:"Japan's biggest club. Outdoor pool, multiple stages, world-class sound. Requires a taxi from Shibuya.",why:"For the serious EDM or house night.",place_id:"ChIJMwFGbIKJGGARBaGQ6KkJJLs"},
          {id:"tok-c3",name:"ATOM Shibuya",lat:35.6583059,lng:139.6954048,rating:3.2,price_low:25,price_high:45,blurb:"Five floors of EDM, tech house, J-EDM. Drink tickets with entry. Top floor smoking only. Walkable from Millennials.",why:"Best multi-floor club near the hotel.",place_id:"ChIJgQQtEqqMGGAR0lBz9of3YVI"},
          {id:"tok-c4",name:"TK Nightclub",lat:35.6609411,lng:139.6985674,rating:4.4,price_low:30,price_high:60,blurb:"VIP-table-focused with a lively dance floor. Hip-hop, R&B, EDM DJs. Better for table service than floor dancing.",why:"If you want table service.",place_id:"ChIJi9W-AKmMGGARgTIvRY42-po"},
          {id:"tok-c5",name:"NEVERLAND Tokyo (Dogenzaka)",lat:35.6589847,lng:139.6955447,rating:4.0,price_low:10,price_high:25,blurb:"Free entry plus unlimited drinks for women, cheap cover for men. Gets crowded. Good first stop or warmup.",why:"Cheapest way to start a night.",place_id:"ChIJAdQxG9GNGGARmH6zAaG5txU"}
        ]
      }
    },

    sapporo: {
      name:"Sapporo", nights:2, dates:"Jul 27-29",
      hero_lat:43.0618, hero_lng:141.3545,
      categories: {
        lodging: [
          {id:"sap-l1",name:"Ten To Ten Hostel",lat:43.0681749,lng:141.3435344,rating:4.1,price_low:25,price_high:50,blurb:"10-min walk from Sapporo Station. Dorms or private rooms. Self check-in via tablet. Clean and modern.",why:"Cheapest option; near the station.",place_id:"ChIJd4o3XKApC18RpDPeoXkUSeo"},
          {id:"sap-l2",name:"Plat Hostel Keikyu Sapporo Sky",lat:43.0522373,lng:141.3572478,rating:4.4,price_low:30,price_high:60,blurb:"Top-reviewed Sapporo hostel: clean, quiet, good showers. Private twin rooms available. Susukino district.",why:"Best-reviewed; solid private room options.",place_id:"ChIJCZ3XB4cpC18R9rCbOSDZnU0"},
          {id:"sap-l3",name:"Hotel + Hostel Sapporo (Tanukikoji)",lat:43.056856,lng:141.3509113,rating:3.8,price_low:30,price_high:55,blurb:"On the Tanukikoji covered shopping arcade. Most central location in Sapporo. Small rooms.",why:"Best location for immediate exploration.",place_id:"ChIJc0AUluopC18R6gJ1aADsvVg"},
          {id:"sap-l4",name:"GRAND HOSTEL LDK Sapporo",lat:43.0538407,lng:141.3453946,rating:3.9,price_low:30,price_high:55,blurb:"Modern hostel 10 min walk from Susukino. Common kitchen, free coffee and tea, card-only floor access.",why:"Solid backup with kitchen access.",place_id:"ChIJMWTwro8pC18Rdz9BDE3RHhQ"}
        ],
        soup_curry: [
          {id:"sap-sc1",name:"Soup Curry GARAKU (Main Restaurant)",lat:43.0583997,lng:141.3588997,rating:4.3,price_low:14,price_high:22,blurb:"The most famous Sapporo soup curry: dashi-forward broth, deeply tender pork, roasted vegetables. Spice levels 1-40. Expect a queue.",why:"The Sapporo classic. A must-eat here.",place_id:"ChIJQ21rhoMpC18RmzhfndITzug"},
          {id:"sap-sc2",name:"Suage+ Soup Curry",lat:43.0557369,lng:141.3512699,rating:4.3,price_low:14,price_high:22,blurb:"GARAKU's rival with bolder spice and charcoal-grilled chicken. LINE app queue so you don't wait in line in person.",why:"Easier queue management; punchier spice.",place_id:"ChIJv0HGVIQpC18Rc2m8zsIZwJE"},
          {id:"sap-sc3",name:"Soup Curry Okushiba (Tabelog No.1)",lat:43.0667859,lng:141.3543390,rating:4.6,price_low:14,price_high:22,blurb:"Tabelog's top-ranked Sapporo curry. Takes orders while you queue so food comes fast once seated. Very fresh ingredients.",why:"Highest-rated by Japanese reviewers.",place_id:"ChIJn8GXRXQpC18ROE27C3HlsNM"}
        ],
        beer: [
          {id:"sap-b1",name:"Sapporo Beer Museum",lat:43.0714671,lng:141.3689124,rating:4.3,price_low:5,price_high:15,blurb:"Free museum in the original 1890 brewery. Paid tasting room: 3-beer classic flight about 1000 yen. Beer-jelly chocolate worth buying.",why:"From your original plan; the icon.",place_id:"ChIJ0fYsL4QpC18Ry-fF7_rGYBM"},
          {id:"sap-b2",name:"Sapporo Beer Garden (AYCE Jingisukan)",lat:43.0713342,lng:141.3690782,rating:4.2,price_low:38,price_high:55,blurb:"All-you-can-eat Hokkaido lamb BBQ plus unlimited draft Sapporo in a historic brick hall. 100-minute slot. Pre-book weekends.",why:"Beer plus the Hokkaido lamb dish in one stop.",place_id:"ChIJ__9PCWwpC18RpHEvsAli2gg"},
          {id:"sap-b3",name:"Sapporo Jingisukan Main Shop (Susukino)",lat:43.0530465,lng:141.3504462,rating:4.1,price_low:20,price_high:35,blurb:"Old-school Genghis Khan joint. Local crowd, about 1250 yen per plate, smoky and unpretentious.",why:"Cheaper and more local than the Beer Garden.",place_id:"ChIJhwg_94UpC18RF0j8TEmLd_o"}
        ],
        ramen: [
          {id:"sap-r1",name:"Sapporo Ramen Haruka (Ramen Alley)",lat:43.0549506,lng:141.3542979,rating:4.8,price_low:12,price_high:20,blurb:"9-seat counter. Triple-cheese miso and spicy miso are the standouts. Long queue so go mid-afternoon.",why:"Highest-rated Sapporo ramen (4.8 stars).",place_id:"ChIJ07FgJIQpC18RYkRNPfQgdvw"},
          {id:"sap-r2",name:"Teshikaga Ramen (Ramen Alley)",lat:43.0548706,lng:141.3543394,rating:4.6,price_low:12,price_high:20,blurb:"Two doors from Haruka. Pork-belly miso plus gyoza set. Separate automated queue system.",why:"Easier to get into; equally classic.",place_id:"ChIJ6bhSnYYpC18RK6nWkDV5tKs"},
          {id:"sap-r3",name:"Sapporo Junren",lat:43.0208306,lng:141.3669134,rating:4.0,price_low:14,price_high:22,blurb:"Old-school butter-corn miso ramen. Rich, lard-topped, hearty. The foundational Sapporo bowl archetype.",why:"For the original style; less touristy.",place_id:"ChIJj5njG2UqC18RAiq9rUkZZ1E"}
        ],
        nature: [
          {id:"sap-n1",name:"Mt. Moiwa Ropeway + Summit",lat:43.022197,lng:141.3224595,rating:4.5,price_low:14,price_high:14,blurb:"2100 yen round trip via ropeway then mini cable car. Panoramic view of Sapporo, mountains, and sea. Best at dusk. Free shuttle bus from tram stop.",why:"Best city panorama in Sapporo.",place_id:"ChIJVxXPRfDVCl8REVDFQkZrz5o"},
          {id:"sap-n2",name:"Takino Suzuran Hillside Park",lat:42.9115157,lng:141.3801515,rating:4.5,price_low:5,price_high:10,blurb:"Large national park about 40 min south by bus. Hiking, waterfall, kochia and sunflower fields in late July. Bus 106 from Makomanai.",why:"From your original plan; full nature day.",place_id:"ChIJnaswN-srdV8RolQuYYUQRRQ"},
          {id:"sap-n3",name:"Maruyama Park + Hokkaido Shrine",lat:43.0557453,lng:141.3126073,rating:4.3,price_low:0,price_high:0,blurb:"Forested city park with Hokkaido's main Shinto shrine. Easy subway access. Good 90-min morning walk.",why:"Easy in-city nature option.",place_id:"ChIJ__9bfcIpC18RoJ9c21tKf2w"},
          {id:"sap-n4",name:"Otaru Day Trip (Canal + Glass Quarter)",lat:43.199041,lng:141.0021176,rating:4.4,price_low:20,price_high:50,blurb:"Historic canal port 45 min by JR (about 750 yen each way). Preserved brick warehouses, music box museum, glass shops, good lunch spots.",why:"Easy half or full-day side trip.",place_id:"ChIJ0UxVV2ThCl8RIZdpda0H7gQ"}
        ],
        onsen: [
          {id:"sap-o1",name:"Kitano Tamayura Soen (City Onsen)",lat:43.0712151,lng:141.3289977,rating:3.9,price_low:5,price_high:8,blurb:"Large modern public onsen near Soen Station. Indoor pools, two outdoor pools, two saunas, cold plunge, tatami rest area. 480 yen entry, open 7am to 1am.",why:"Best full-facility onsen accessible from central Sapporo.",place_id:"ChIJRdoaQa8pC18RsBckr9CRRkA"},
          {id:"sap-o2",name:"Fushimi Onsen (Neighborhood Sento)",lat:43.0358562,lng:141.3338589,rating:4.0,price_low:4,price_high:5,blurb:"Traditional Showa-era neighborhood bathhouse. Maifan stone bath plus medicinal bath. 500 yen entry. Genuine local experience.",why:"For the authentic sento experience.",place_id:"ChIJ12MaeAQqC18RbQbUlu7BG4w"}
        ],
        club: [
          {id:"sap-c1",name:"Music Bar SIDE:K (K-pop, Susukino)",lat:43.053874,lng:141.352782,rating:4.9,price_low:15,price_high:30,blurb:"K-pop themed bar with all-you-can-drink option. Bilingual staff. Small, fun, easy to drop into.",why:"Easy first night option.",place_id:"ChIJO7SOQgApC18RAMnxoniz1aI"},
          {id:"sap-c2",name:"Rock Bar Fxxk Up",lat:43.0542253,lng:141.3507467,rating:4.9,price_low:10,price_high:25,blurb:"6th-floor rock and metal bar. Bilingual owners Nori and Chuck. Good whisky. One of the friendliest bars in Japan.",why:"Best bar for actual conversation.",place_id:"ChIJHawM-oIpC18RwhzWuQ72K7s"},
          {id:"sap-c3",name:"SANGO Sapporo by Riviera",lat:43.0530086,lng:141.3531337,rating:4.9,price_low:20,price_high:40,blurb:"Modern club and lounge in Susukino. Tokyo-style design and music.",why:"Best actual club night in Sapporo.",place_id:"ChIJG9lfXAApC18RS8BrocTlNlc"}
        ]
      }
    },

    seoul: {
      name:"Seoul", nights:3, dates:"Jul 29 - Aug 1",
      hero_lat:37.5535, hero_lng:126.9700,
      categories: {
        bbq: [
          {id:"seo-b1",name:"Mongvely KBBQ Myeongdong (AYCE)",lat:37.561357,lng:126.9844162,rating:4.9,price_low:22,price_high:35,blurb:"All-you-can-eat BBQ about 29000 KRW per person plus 2500 KRW unlimited drinks. Self-service grill. 4.9 stars in Myeongdong.",why:"Best KBBQ value in the city.",place_id:"ChIJgcs2nlujfDURZe-3Vni6FcE",images:["images/seoul/seo-b1-1.jpg","images/seoul/seo-b1-2.jpg","images/seoul/seo-b1-3.jpg"]},
          {id:"seo-b2",name:"Wangbijip Myeongdong (premium)",lat:37.5617081,lng:126.9864459,rating:4.5,price_low:35,price_high:70,blurb:"Premium cuts, staff grill for you. Smaller portions but higher quality than AYCE places.",why:"When quality matters more than quantity.",place_id:"ChIJhwklg_qifDURQDLm0Ant2yQ",images:["images/seoul/seo-b2-1.jpg","images/seoul/seo-b2-2.jpg","images/seoul/seo-b2-3.jpg"]},
          {id:"seo-b3",name:"Bogwangjung Itaewon (pork belly specialist)",lat:37.5333181,lng:126.9945515,rating:4.9,price_low:30,price_high:55,blurb:"4.9 star samgyeopsal joint. Chef cooks at the table and coaches you through the meal. Book ahead.",why:"Best pork belly experience in Seoul.",place_id:"ChIJnbqVZSSjfDURXy6xhCsHEN8",images:["images/seoul/seo-b3-1.jpg","images/seoul/seo-b3-2.jpg","images/seoul/seo-b3-3.jpg"]},
          {id:"seo-b4",name:"MapleTree House Itaewon (galbi)",lat:37.535049,lng:126.9939672,rating:4.3,price_low:50,price_high:90,blurb:"Upscale galbi specialist. Jeju black pork also excellent. English-friendly staff.",why:"Most refined KBBQ option.",place_id:"ChIJP1IxUUqifDUR2NBF3aY0UUs",images:["images/seoul/seo-b4-1.jpg","images/seoul/seo-b4-2.jpg","images/seoul/seo-b4-3.jpg"]},
          {id:"seo-mp1",name:"Mapo Galmaegi KBBQ",lat:37.5487,lng:126.9524,rating:4.4,price_low:20,price_high:40,blurb:"Thinly sliced pork neck (galmaegi-sal) grilled at the table: leaner, cheaper and more intensely flavoured than belly, beloved by Seoul regulars. Mapo has a concentration of galmaegi-sal specialists.",why:"Local-favourite cut most tourists miss; cheaper than samgyeopsal."}
        ],
        karaoke: [
          {id:"seo-k1",name:"Soo Karaoke Club Hongdae (luxury branch)",lat:37.5511444,lng:126.9211118,rating:4.5,price_low:18,price_high:35,blurb:"Luxury noraebang with a famous 2-floor room and floor-to-ceiling windows facing Hongdae street. Large English song selection.",why:"Premium Seoul noraebang experience.",place_id:"ChIJHf8LudqYfDUR4AAwAqVRKag",images:["images/seoul/seo-k1-1.jpg","images/seoul/seo-k1-2.jpg","images/seoul/seo-k1-3.jpg"]}
        ],
        cafe: [
          {id:"seo-cf1",name:"Roof Cat Me (Hongdae)",lat:37.5549057,lng:126.9221227,rating:4.9,price_low:9,price_high:14,blurb:"Largest cat cafe. Spacious, fountain, unlimited drinks included. Cats calm and well-treated.",why:"Best cat cafe: clean and not overcrowded.",place_id:"ChIJdzXsXQCZfDURXLVUzFG2dCg",images:["images/seoul/seo-cf1-1.jpg","images/seoul/seo-cf1-2.jpg","images/seoul/seo-cf1-3.jpg"]},
          {id:"seo-cf2",name:"Abandoned Cat Cafe Hongdae (rescue)",lat:37.5519294,lng:126.9229064,rating:4.2,price_low:8,price_high:12,blurb:"Rescue-cat cafe. Proceeds fund the cats. Many survivor cats and very affectionate.",why:"Ethical alternative.",place_id:"ChIJD5rIz3-ZfDURj2skyByS7D0",images:["images/seoul/seo-cf2-1.jpg","images/seoul/seo-cf2-2.jpg","images/seoul/seo-cf2-3.jpg"]},
          {id:"seo-cf3",name:"Meidcafe Cawai (Hongdae maid and butler cafe)",lat:37.5500385,lng:126.9233474,rating:5.0,price_low:15,price_high:30,blurb:"Maid and butler cafe with live performances including K-pop covers throughout the afternoon. 5 stars, bilingual staff.",why:"Top-rated maid cafe on your list.",place_id:"ChIJ--5fcH6ZfDUR7C0ltLCZjeA",images:["images/seoul/seo-cf3-1.jpg","images/seoul/seo-cf3-2.jpg","images/seoul/seo-cf3-3.jpg"]},
          {id:"seo-cf4",name:"Omai Maid Cafe Hongdae",lat:37.5531501,lng:126.9220227,rating:4.9,price_low:15,price_high:30,blurb:"Underground maid cafe with a cozy aesthetic and some bilingual staff.",why:"Alternative if Cawai has a queue.",place_id:"ChIJ64zQp7OZfDUR_vU9MWg2Ih0",images:["images/seoul/seo-cf4-1.jpg","images/seoul/seo-cf4-2.jpg","images/seoul/seo-cf4-3.jpg"]},
          {id:"seo-cf5",name:"943 Kings Cross (Harry Potter cafe)",lat:37.5529807,lng:126.9208140,rating:4.7,price_low:15,price_high:25,blurb:"Multi-floor Harry Potter themed cafe: interactive elements, alcoholic butter beer, Hagrid cake.",why:"Quirky non-cat alternative.",place_id:"ChIJEadTU22ZfDUR5a0eGJIKQnA",images:["images/seoul/seo-cf5-1.jpg","images/seoul/seo-cf5-2.jpg","images/seoul/seo-cf5-3.jpg"]},
          {id:"seo-cf6",name:"Stylenanda Pink Pool Cafe",lat:37.5545473,lng:126.9274387,rating:4.0,price_low:10,price_high:18,blurb:"Top floor of Stylenanda flagship. Pink everything. Pool may or may not be operational. Drinks average but the space is the point.",why:"From your original plan; photo destination.",place_id:"ChIJK5kufMGYfDUR6DOKgF9uILk",images:["images/seoul/seo-cf6-1.jpg","images/seoul/seo-cf6-2.jpg","images/seoul/seo-cf6-3.jpg"]},
          {id:"seo-cf7",name:"Thanks Nature Cafe (Sheep Cafe, Hongdae)",lat:37.5556679,lng:126.9235374,rating:4.2,price_low:8,price_high:14,blurb:"Two real sheep live in a pen outside this Hongdae basement cafe. Pet them, then have a waffle and latte inside. Free to visit with a drink order.",why:"Pure novelty; the only sheep cafe in Seoul.",place_id:"",images:["images/seoul/seo-cf7-1.jpg","images/seoul/seo-cf7-2.jpg","images/seoul/seo-cf7-3.jpg"]},
          {id:"seo-cf8",name:"Cafe Onion Anguk (Hanok Bakery Cafe)",lat:37.5765577,lng:126.9856024,rating:4.4,price_low:6,price_high:14,blurb:"A century-old hanok turned stunning bakery-cafe between Gyeongbokgung and Changdeokgung. Courtyard seating, floor cushions, and trays of just-baked bread — get the sugar-dusted 'pandoro'.",why:"Most beautiful cafe in the old city; pairs with a palace day.",place_id:"",images:["images/seoul/seo-cf8-1.jpg","images/seoul/seo-cf8-2.jpg","images/seoul/seo-cf8-3.jpg"]},
          {id:"seo-ir4",name:"O'Kitchen (Hannam brunch cafe)",lat:37.5365,lng:127.0010,rating:4.5,price_low:14,price_high:22,blurb:"Hannam beloved brunch-and-lunch cafe: open-face sandwiches, grain bowls and weekend egg dishes in a light-filled room. A neighbourhood institution.",why:"Best sit-down brunch in Hannam; earned rather than just Instagram-famous."},
          {id:"seo-ir5",name:"Tartine Hannam (sourdough bakery)",lat:37.5364,lng:127.0008,rating:4.4,price_low:9,price_high:16,blurb:"A Korean outpost of San Francisco legendary sourdough bakery, in a striking minimalist Hannam space. Country bread, morning buns and very good coffee.",why:"Best bread in Seoul; worth the detour from Itaewon."},
          {id:"seo-sc1",name:"Fritz Coffee Company (Seongsu)",lat:37.5456,lng:127.0352,rating:4.6,price_low:6,price_high:12,blurb:"One of Seoul finest specialty roasters, in a beautifully converted Seongsu warehouse. Direct-trade lots, precise extraction and cinnamon rolls that sell out by 11am.",why:"The cafe that defines Seoul specialty coffee; a must-visit in Seongsu."},
          {id:"seo-sc3",name:"Daelim Changgo (Seongsu warehouse cafe)",lat:37.5445,lng:127.0363,rating:4.3,price_low:6,price_high:10,blurb:"A 1960s factory warehouse transformed into a multi-level cafe and art space: exposed brick, skylights and a sprawling outdoor terrace. The most atmospheric hangout in Seongsu.",why:"Best cafe atmosphere in Seongsu; the warehouse-industrial vibe at its best."},
          {id:"seo-sc4",name:"Able (Seongsu Korean fusion brunch)",lat:37.5440,lng:127.0370,rating:4.4,price_low:12,price_high:18,blurb:"A chic Seongsu brunch spot blending Korean and Western flavours: doenjang-glazed chicken plates, grain bowls and excellent lattes in a Scandi-meets-Seoul dining room.",why:"Best lunch in Seongsu after Seoul Forest."},
          {id:"seo-ant1",name:"Anthracite Hongdae (specialty coffee)",lat:37.5565,lng:126.9248,rating:4.5,price_low:5,price_high:10,blurb:"A converted shoe factory turned landmark specialty coffee shop: exposed industrial bones, 7m ceilings and outstanding single-origin pour-overs roasted in-house. Seoul most photographed coffee interior.",why:"The Hongdae cafe that launched Seoul specialty-coffee scene."},
          {id:"seo-ins2",name:"Cafe Bora (Bukchon, matcha)",lat:37.5808,lng:126.9833,rating:4.4,price_low:8,price_high:14,blurb:"An iconic Bukchon cafe famous for vibrant purple-rice tteok latte and matcha soft-serve, served in a tiny hanok room near the village entrance. Always a queue but moves fast.",why:"Most photogenic cafe in the old city; earns its reputation."}
        ],
        cocktail_bar: [
          {id:"seo-cb1",name:"Coley (Gyeongnidan, Itaewon area)",lat:37.5367664,lng:126.9870627,rating:4.8,price_low:20,price_high:40,blurb:"Craft cocktail bar run by a Korean-Canadian couple. Custom drinks made to taste. Open until 3:30am.",why:"4.8 stars; best cocktails in Seoul.",place_id:"ChIJsXwM20ijfDURb3e7ZwXv3qQ",images:["images/seoul/seo-cb1-1.jpg","images/seoul/seo-cb1-2.jpg","images/seoul/seo-cb1-3.jpg"]},
          {id:"seo-cb2",name:"Blacklist Bar (Itaewon)",lat:37.5338675,lng:126.9887904,rating:4.6,price_low:20,price_high:45,blurb:"Rooftop bar with exceptional bar food: filet-o-fish sandwich, beef jerky, spicy chicken sandwich. Dog friendly.",why:"Best bar food in Seoul.",place_id:"ChIJIbP9A0qifDURP16KTlKKx_c",images:["images/seoul/seo-cb2-1.jpg","images/seoul/seo-cb2-2.jpg","images/seoul/seo-cb2-3.jpg"]},
          {id:"seo-cb3",name:"DUSK TILL DAWN BAR (Itaewon)",lat:37.5352866,lng:126.9918603,rating:4.9,price_low:22,price_high:45,blurb:"Upscale cocktail lounge. Jazz at perfect volume. Cozy booths and warm lighting.",why:"4.9 stars; best atmosphere bar in Itaewon.",place_id:"ChIJuawrmC-jfDURImXeKylbCVs",images:["images/seoul/seo-cb3-1.jpg","images/seoul/seo-cb3-2.jpg","images/seoul/seo-cb3-3.jpg"]},
          {id:"seo-cb4",name:"Alice Cheongdam (Speakeasy)",lat:37.5246,lng:127.0410,rating:4.6,price_low:25,price_high:50,blurb:"Wonderland-themed Cheongdam speakeasy entered through a flower shop; theatrical, award-winning cocktails. An Asia's-50-Best regular.",why:"Seoul's most famous craft-cocktail destination.",place_id:"",images:["images/seoul/seo-cb4-1.jpg","images/seoul/seo-cb4-2.jpg","images/seoul/seo-cb4-3.jpg"]},
          {id:"seo-cb5",name:"Charles H. (Four Seasons)",lat:37.5687,lng:126.9760,rating:4.7,price_low:25,price_high:55,blurb:"Dark, plush hotel speakeasy repeatedly named among Asia's 50 Best Bars; impeccable classics and a 'bespoke' menu built around your taste.",why:"Best hotel bar; serious cocktail craft.",place_id:"",images:["images/seoul/seo-cb5-1.jpg","images/seoul/seo-cb5-2.jpg","images/seoul/seo-cb5-3.jpg"]},
          {id:"seo-cb6",name:"Bar Cham (Itaewon, Korean spirits)",lat:37.5375,lng:126.9913,rating:4.6,price_low:16,price_high:35,blurb:"Intimate Itaewon bar dedicated to creative cocktails made with traditional Korean spirits — soju, makgeolli and goryangju — alongside Korean whisky. Small plates designed for pairing. Mostly local crowd.",why:"Best bar for discovering Korean spirits in a contemporary setting.",images:["images/seoul/seo-cb6-1.jpg","images/seoul/seo-cb6-2.jpg","images/seoul/seo-cb6-3.jpg"]},
          {id:"seo-cb7",name:"Southside Parlor (Itaewon)",lat:37.5345,lng:126.9924,rating:4.5,price_low:16,price_high:40,blurb:"Americana dive bar in Itaewon: wood-smoked BBQ ribs, loaded burgers, creative cocktails and cold draft beer. Pool table, dog-friendly outdoor patio, no dress code. The most reliably fun casual bar in the neighbourhood.",why:"Best bar food in Itaewon; comfortable and unpretentious.",images:["images/seoul/seo-cb7-1.jpg","images/seoul/seo-cb7-2.jpg","images/seoul/seo-cb7-3.jpg"]},
          {id:"seo-hb4",name:"Pistil (Haebangchon rooftop bar)",lat:37.5380,lng:126.9810,rating:4.4,price_low:8,price_high:16,blurb:"An intimate rooftop bar in Haebangchon, the hillside neighbourhood above Itaewon: fairy lights, Namsan views and a natural-wine list. The low-key Itaewon alternative.",why:"Best rooftop for a quiet drink near Itaewon; more relaxed than the strip."},
          {id:"seo-hb5",name:"Bab Ajeossi Bar (Ikseon-dong)",lat:37.5745,lng:126.9880,rating:4.5,price_low:10,price_high:18,blurb:"A popular Ikseon-dong cocktail bar with a quirky old-Seoul aesthetic: makgeolli, domestic spirits and creative low-abv cocktails in a crowded alley setting.",why:"Best bar in the Ikseon alley complex; the local favourite."},
          {id:"seo-hb6",name:"Blackbird (Insadong cocktail bar)",lat:37.5742,lng:126.9906,rating:4.5,price_low:12,price_high:20,blurb:"A craft cocktail bar in the Insadong neighbourhood with an avian theme: serious classic cocktails and an extensive whisky menu in a cosy mid-century interior.",why:"Best cocktail bar near the old city; ideal after Ikseon wandering."},
          {id:"seo-hb7",name:"Bar de Nuit (Itaewon)",lat:37.5345,lng:126.9930,rating:4.4,price_low:12,price_high:22,blurb:"A French-inspired Itaewon cocktail bar: seasonal sparkling-wine cocktails, elegant small plates and an unhurried pace. The quieter, more conversational end of the Itaewon bar strip.",why:"Best bar for a slow quality drink in Itaewon without the party energy."},
          {id:"seo-hb8",name:"Woo Saeng Go (Ikseon makgeolli bar)",lat:37.5740,lng:126.9902,rating:4.4,price_low:10,price_high:18,blurb:"A mellow craft-makgeolli and natural-wine bar in the Ikseon-dong alley complex: exposed brick, wooden tables and a rotating list of small-batch Korean rice wines paired with jeon pancakes.",why:"Best craft makgeolli in the old city; great late-night vibe."},
          {id:"seo-chm1",name:"Gin Gin Bar (Cheongdam speakeasy)",lat:37.5246,lng:127.0412,rating:4.5,price_low:15,price_high:25,blurb:"A Cheongdam speakeasy dedicated to gin: 70-plus labels arranged by botanical profile, with precise tonic service and rotating signature cocktails. Hidden-door entry.",why:"Best gin bar in Seoul; pairs perfectly with the Alice Cheongdam neighbourhood."}
        ],
        craft_beer: [
          {id:"seo-br1",name:"Magpie ITW Brewshop (Itaewon taproom)",lat:37.5393931,lng:126.9875108,rating:4.5,price_low:15,price_high:30,blurb:"Seoul's top craft beer brand. Korean IPA, sours, seasonal stouts. Outdoor seating, mixed local and expat crowd.",why:"Best craft beer in Seoul.",place_id:"ChIJyYpst0iifDURBTGdpA0-huQ",images:["images/seoul/seo-br1-1.jpg","images/seoul/seo-br1-2.jpg","images/seoul/seo-br1-3.jpg"]},
          {id:"seo-br2",name:"White Rabbit Tap House (Itaewon)",lat:37.5391291,lng:126.9873379,rating:4.4,price_low:15,price_high:35,blurb:"Owner-run whisky and craft beer bar. Exceptional Korean lager. Extensive whisky wall. Very welcoming host.",why:"Best for whisky plus Korean craft beer.",place_id:"ChIJ5d_8u0iifDURgBm7rieEQik",images:["images/seoul/seo-br2-1.jpg","images/seoul/seo-br2-2.jpg","images/seoul/seo-br2-3.jpg"]},
          {id:"seo-hb1",name:"Craftbros Hongdae (craft beer bar)",lat:37.5556,lng:126.9250,rating:4.4,price_low:9,price_high:18,blurb:"A relaxed Hongdae craft-beer bar with 12 rotating taps: Korean and international IPAs, sours and wheat beers. Good bar food, garden terrace and no dress code.",why:"Best craft beer in Hongdae; the relaxed warmup before a club night."}
        ],
        dessert: [
          {id:"seo-d1",name:"Samcheong Bingsu (near Bukchon)",lat:37.5828813,lng:126.9819321,rating:4.5,price_low:12,price_high:18,blurb:"Traditional bingsu in a hanok cafe near Bukchon. Black sesame, red bean, seasonal fruit flavors. Fluffy properly textured ice.",why:"Best bingsu; pairs with Bukchon visit.",place_id:"ChIJ9wH82cWifDUR3B4TKFGNmIY",images:["images/seoul/seo-d1-1.jpg","images/seoul/seo-d1-2.jpg","images/seoul/seo-d1-3.jpg"]},
          {id:"seo-d2",name:"Sulbing Hongdae (shaved milk ice)",lat:37.5553194,lng:126.9226786,rating:4.2,price_low:10,price_high:16,blurb:"Shaved frozen milk, smoother than regular bingsu. Open until midnight. Injeolmi and tiramisu flavors.",why:"Open late; walking distance from Nine Brick.",place_id:"ChIJI0qfR8OYfDUR2ZtOVHA-Wec",images:["images/seoul/seo-d2-1.jpg","images/seoul/seo-d2-2.jpg","images/seoul/seo-d2-3.jpg"]}
        ],
        market: [
          {id:"seo-m1",name:"Gwangjang Market",lat:37.5700398,lng:126.9996036,rating:4.2,price_low:15,price_high:30,blurb:"Seoul's main food market. Bindaetteok (mung bean pancake), mayak gimbap, mung bean bibimbap. Open until 10:30pm.",why:"From your original plan; anchor food experience.",place_id:"ChIJm3V0fu2ifDURRJ8IMUijVtY",images:["images/seoul/seo-m1-1.jpg","images/seoul/seo-m1-2.jpg","images/seoul/seo-m1-3.jpg"]},
          {id:"seo-m2",name:"Myeongdong Night Market",lat:37.5616685,lng:126.9858438,rating:4.4,price_low:15,price_high:30,blurb:"Street food market 5pm-1am: cheese corn dogs, tornado potatoes, egg bread, mochi ice cream.",why:"On your doorstep if staying in Myeongdong.",place_id:"ChIJqb-ne_CifDURR-yH8a3sjXM",images:["images/seoul/seo-m2-1.jpg","images/seoul/seo-m2-2.jpg","images/seoul/seo-m2-3.jpg"]}
        ],
        clinic: [
          {id:"seo-cl1",name:"BLS Clinic (Gangnam)",lat:37.5249282,lng:127.0438871,rating:5.0,price_low:80,price_high:300,blurb:"5 star K-beauty clinic. Facials, peels, laser toning. Consistent international reviews. No upsell pressure.",why:"Best overall rating.",place_id:"ChIJMz9wwXmkfDURMmPLfzfsRec",images:["images/seoul/seo-cl1-1.jpg","images/seoul/seo-cl1-2.jpg","images/seoul/seo-cl1-3.jpg"]},
          {id:"seo-cl2",name:"Min Clinic (Apgujeong)",lat:37.5223746,lng:127.0377720,rating:5.0,price_low:100,price_high:400,blurb:"Upscale clinic for specific procedures: botox, nose filler, 10Therma lift. Doctor-led consultations.",why:"For specific procedures rather than facials.",place_id:"ChIJb8xEEXikfDUR1tj9x7iICQs",images:["images/seoul/seo-cl2-1.jpg","images/seoul/seo-cl2-2.jpg","images/seoul/seo-cl2-3.jpg"]},
          {id:"seo-cl3",name:"MUSE Clinic (Gangnam)",lat:37.5028175,lng:127.0257065,rating:4.6,price_low:80,price_high:300,blurb:"High-volume clinic with many treatment options. Very popular with international visitors. English support.",why:"Best price-to-volume ratio.",place_id:"ChIJI5TInVihfDUROi_xU2LFqxM",images:["images/seoul/seo-cl3-1.jpg","images/seoul/seo-cl3-2.jpg","images/seoul/seo-cl3-3.jpg"]},
          {id:"seo-cl4",name:"Forena Clinic (Hongdae, walk-in)",lat:37.5540,lng:126.9240,rating:4.5,price_low:35,price_high:70,blurb:"Doctor-run English-speaking Hongdae clinic 1 min from the station: Aqua Peel ~₩60,000 ($45), laser toning, and skin boosters at local Korean prices. Walk-ins welcome, zero upsell.",why:"Budget facial at Korean local prices; most accessible for tourists.",place_id:"",images:["images/seoul/seo-cl4-1.jpg","images/seoul/seo-cl4-2.jpg","images/seoul/seo-cl4-3.jpg"]}
        ],
        chicken: [
          {id:"seo-ch1",name:"Dae Wang Tong Dak (Myeongdong, retro)",lat:37.5618464,lng:126.987191,rating:4.9,price_low:18,price_high:30,blurb:"Late-night retro fried chicken and pocha vibes. 4.9 stars. Open until 1am. Family owners. Frequently described as best meal in Seoul.",why:"Highest-rated chicken option.",place_id:"ChIJOwtwJgCjfDURWagYBNyydgs",images:["images/seoul/seo-ch1-1.jpg","images/seoul/seo-ch1-2.jpg","images/seoul/seo-ch1-3.jpg"]},
          {id:"seo-ch2",name:"Kyochon Chicken Dongdaemun (24h)",lat:37.5713239,lng:127.0106797,rating:4.5,price_low:20,price_high:35,blurb:"The first Kyochon location, open 24h. Soy-garlic and honey classics. Cassava chips plus Cass beer.",why:"Iconic chain; always open.",place_id:"ChIJA_TdWTqjfDURc-LwCzoHRUQ",images:["images/seoul/seo-ch2-1.jpg","images/seoul/seo-ch2-2.jpg","images/seoul/seo-ch2-3.jpg"]},
          {id:"seo-ch3",name:"Kkanbu Chicken (Myeongdong)",lat:37.5616858,lng:126.9861898,rating:4.6,price_low:20,price_high:30,blurb:"Crispy well-marinated KFC chain in Myeongdong. Garlic soy is the signature. English tablet ordering.",why:"Most convenient from Myeongdong.",place_id:"ChIJy2DnyQ2jfDURQj9don6TouA",images:["images/seoul/seo-ch3-1.jpg","images/seoul/seo-ch3-2.jpg","images/seoul/seo-ch3-3.jpg"]}
        ],
        sight: [
          {id:"seo-s1",name:"Bukchon Hanok Village",lat:37.5814696,lng:126.9849519,rating:4.4,price_low:0,price_high:0,blurb:"Traditional hanok village on a hillside. Narrow alleys, tile-roofed houses. Visiting hours 10am-5pm.",why:"Free, photogenic, half-day.",place_id:"ChIJT8H4r9qifDURmuXJ_6m6vM0",images:["images/seoul/seo-s1-1.jpg","images/seoul/seo-s1-2.jpg","images/seoul/seo-s1-3.jpg"]},
          {id:"seo-s2",name:"N Seoul Tower (Namsan)",lat:37.5511694,lng:126.9882266,rating:4.5,price_low:15,price_high:22,blurb:"Iconic tower on Namsan mountain. Hike up (30 min steep) or cable car. Good sunset views over the city.",why:"Classic Seoul skyline view.",place_id:"ChIJqWqOqFeifDURpYJ5LnxX-Fw",images:["images/seoul/seo-s2-1.jpg","images/seoul/seo-s2-2.jpg","images/seoul/seo-s2-3.jpg"]},
          {id:"seo-s3",name:"Seoul Sky (Lotte World Tower)",lat:37.5125295,lng:127.102305,rating:4.6,price_low:23,price_high:30,blurb:"World's highest glass-floor observation deck (123F). 360 degree views; sunset is the move.",why:"Higher than N Tower; more modern.",place_id:"ChIJu7dpc45FezURhLMS5U5eaJk",images:["images/seoul/seo-s3-1.jpg","images/seoul/seo-s3-2.jpg","images/seoul/seo-s3-3.jpg"]},
          {id:"seo-s4",name:"Gyeongbokgung Palace",lat:37.5796214,lng:126.9769796,rating:4.6,price_low:2,price_high:3,blurb:"Seoul's grand main palace (1395). Catch the changing-of-the-guard ceremony at the gate. Free entry if you arrive in rented hanbok. Closed Tuesdays.",why:"The headline historic site; pairs with Bukchon.",place_id:"",images:["images/seoul/seo-s4-1.jpg","images/seoul/seo-s4-2.jpg","images/seoul/seo-s4-3.jpg"]},
          {id:"seo-s5",name:"Changdeokgung Palace & Secret Garden",lat:37.5794155,lng:126.991002,rating:4.6,price_low:3,price_high:8,blurb:"UNESCO-listed palace whose Huwon (Secret Garden) is visited by timed guided tour only — book ahead. The most serene of the five palaces.",why:"Less crowded than Gyeongbokgung; the garden is the draw.",place_id:"",images:["images/seoul/seo-s5-1.jpg","images/seoul/seo-s5-2.jpg","images/seoul/seo-s5-3.jpg"]},
          {id:"seo-s6",name:"Dongdaemun Design Plaza (DDP)",lat:37.566536,lng:127.009193,rating:4.4,price_low:0,price_high:0,blurb:"Zaha Hadid's flowing silver landmark. Free to wander the curves day or night; LED rose field and night market outside. Rotating design exhibits inside (paid).",why:"Free architecture spectacle, best after dark.",place_id:"",images:["images/seoul/seo-s6-1.jpg","images/seoul/seo-s6-2.jpg","images/seoul/seo-s6-3.jpg"]},
          {id:"seo-s8",name:"Starfield Library (COEX Mall)",lat:37.5125701,lng:127.0589571,rating:4.5,price_low:0,price_high:0,blurb:"Free two-story open library with 13m floor-to-ceiling bookshelves inside the COEX mall. Hugely photogenic. Pair with the aquarium and food court.",why:"Free, air-conditioned, iconic photo spot.",place_id:"",images:["images/seoul/seo-s8-1.jpg","images/seoul/seo-s8-2.jpg","images/seoul/seo-s8-3.jpg"]},
          {id:"seo-s9",name:"Ihwa Mural Village (Naksan)",lat:37.5797501,lng:127.0040368,rating:4.2,price_low:0,price_high:0,blurb:"Hillside neighborhood covered in murals and sculptures, beside the Naksan fortress wall. Steep stairs reward you with skyline views. Free; be quiet — people live here.",why:"Free, photogenic walk with a great city view.",place_id:"",images:["images/seoul/seo-s9-1.jpg","images/seoul/seo-s9-2.jpg","images/seoul/seo-s9-3.jpg"]}
        ],
        show: [
          {id:"seo-sh1",name:"NANTA Theatre Myeongdong",lat:37.5635748,lng:126.9836186,rating:4.5,price_low:40,price_high:65,blurb:"90-minute non-verbal percussion comedy set in a kitchen. No Korean required. Interactive: someone from the audience gets pulled on stage.",why:"From your original plan; the iconic show.",place_id:"ChIJEbpmM_CifDURKJZq-oh9uxo",images:["images/seoul/seo-sh1-1.jpg","images/seoul/seo-sh1-2.jpg","images/seoul/seo-sh1-3.jpg"]},
          {id:"seo-sh2",name:"Hongdae NANTA Theatre",lat:37.5530872,lng:126.9211193,rating:4.6,price_low:40,price_high:65,blurb:"Same show, Hongdae location. Smaller theater, slightly more intimate.",why:"More convenient if staying in Hongdae.",place_id:"ChIJqY5Cd46ifDURue6jfGxGb28",images:["images/seoul/seo-sh2-1.jpg","images/seoul/seo-sh2-2.jpg","images/seoul/seo-sh2-3.jpg"]}
        ],
        noodle: [
          {id:"seo-no1",name:"Myeongdong Kyoja (Michelin)",lat:37.5625266,lng:126.985609,rating:4.2,price_low:10,price_high:14,blurb:"Michelin-recognized 4-item shop: kalguksu (knife-cut noodles), mandu (dumplings), bibim noodle, cold noodle. Queue moves fast.",why:"Quick, excellent, cheap. From your original plan.",place_id:"ChIJW7FBDfCifDURHTpisLbVUH0",images:["images/seoul/seo-no1-1.jpg","images/seoul/seo-no1-2.jpg","images/seoul/seo-no1-3.jpg"]},
          {id:"seo-no2",name:"Jajangmyeon & Tangsuyuk (Korean-Chinese)",lat:37.5493,lng:126.9520,rating:4.3,price_low:9,price_high:20,blurb:"Jajangmyeon (noodles in black bean paste) and tangsuyuk (sweet-and-sour pork) are Korea's beloved Chinese-derived comfort food — a uniquely Korean interpretation with no close equivalent in China. Find it in any neighborhood, cheapest in Mapo.",why:"Something completely different; Korean-Chinese is its own cuisine.",images:["images/seoul/seo-no2-1.jpg","images/seoul/seo-no2-2.jpg","images/seoul/seo-no2-3.jpg"]},
          {id:"seo-no3",name:"Kalguksu (hand-cut noodles, Jongno)",lat:37.5738,lng:126.9860,rating:4.4,price_low:9,price_high:14,blurb:"Hand-cut wheat noodles in a deep anchovy broth — the Korean equivalent of chicken noodle soup. Insadong and Jongno have dedicated shops where halmeoni still cuts noodles to order. Clam or kimchi varieties.",why:"The most comforting $10 bowl in Seoul.",images:["images/seoul/seo-no3-1.jpg","images/seoul/seo-no3-2.jpg","images/seoul/seo-no3-3.jpg"]},
          {id:"seo-no4",name:"Woo Rae Ok (naengmyeon, since 1946)",lat:37.5557,lng:126.9975,rating:4.5,price_low:14,price_high:22,blurb:"One of Seoul's oldest restaurants (est. 1946), famous for Pyongyang-style mul-naengmyeon — buckwheat noodles in ice-cold beef broth, topped with radish kimchi and a hard-boiled egg. Also serves excellent galbi.",why:"The definitive naengmyeon experience in its most classic form.",images:["images/seoul/seo-no4-1.jpg","images/seoul/seo-no4-2.jpg","images/seoul/seo-no4-3.jpg"]}
        ],
        experience: [
          {id:"seo-e1",name:"Dragon Hill Spa (Jjimjilbang, Yongsan)",lat:37.5349662,lng:126.9646767,rating:4.1,price_low:12,price_high:25,blurb:"7-floor 24h Korean spa: hot pools, themed sauna rooms (jade, salt, charcoal), outdoor deck, food court, sleeping halls. Pay once, stay all day. Rent a 'jjimjilbang' outfit at the door.",why:"The quintessential Korean spa day; great jet-lag reset.",place_id:"",images:["images/seoul/seo-e1-1.jpg","images/seoul/seo-e1-2.jpg","images/seoul/seo-e1-3.jpg"]},
          {id:"seo-e2",name:"Yeouido Hangang Park (Han River)",lat:37.5285145,lng:126.9337764,rating:4.5,price_low:0,price_high:0,blurb:"Riverside park that is Seoul's living room: rent tandem bikes, order fried chicken and ramyeon to the lawn, watch the Banpo Bridge rainbow fountain at night. Free to enter.",why:"Free, very local, perfect warm-evening hangout.",place_id:"",images:["images/seoul/seo-e2-1.jpg","images/seoul/seo-e2-2.jpg","images/seoul/seo-e2-3.jpg"]},
          {id:"seo-e3",name:"Trick Eye Museum (Hongdae)",lat:37.5503938,lng:126.9217733,rating:4.3,price_low:12,price_high:18,blurb:"Interactive 3D optical-illusion museum — pose inside painted scenes via the AR app. Ice museum and love museum included. Pure silly-photo fun.",why:"Rainy-day backup; great photos with zero effort.",place_id:"",images:["images/seoul/seo-e3-1.jpg","images/seoul/seo-e3-2.jpg","images/seoul/seo-e3-3.jpg"]},
          {id:"seo-e4",name:"Lotte World (Theme Park)",lat:37.5111158,lng:127.0980267,rating:4.4,price_low:35,price_high:50,blurb:"Half indoor, half outdoor ('Magic Island' on the lake) theme park with real roller coasters. One-day passport covers all rides. Less crowded on weekdays.",why:"A full day of rides without leaving the city.",place_id:"",images:["images/seoul/seo-e4-1.jpg","images/seoul/seo-e4-2.jpg","images/seoul/seo-e4-3.jpg"]}
        ],
        korean_food: [
          {id:"seo-kf1",name:"Tosokchon Samgyetang (Seochon)",lat:37.5779,lng:126.9711,rating:4.3,price_low:14,price_high:20,blurb:"Seoul's most famous samgyetang — a whole young chicken stuffed with ginseng, rice and jujube in a milky broth, in a rambling hanok near Gyeongbokgung. Expect a queue.",why:"The definitive ginseng-chicken-soup; pairs with the palace.",place_id:"",images:["images/seoul/seo-kf1-1.jpg","images/seoul/seo-kf1-2.jpg","images/seoul/seo-kf1-3.jpg"]},
          {id:"seo-kf2",name:"Hadongkwan (Myeongdong gomtang)",lat:37.5648,lng:126.9853,rating:4.3,price_low:12,price_high:18,blurb:"An 80-year-old institution serving essentially one dish: gomtang, a clean simmered-beef-and-rice soup. Open until it sells out in the early afternoon.",why:"Michelin Bib comfort food; fast and pure.",place_id:"",images:["images/seoul/seo-kf2-1.jpg","images/seoul/seo-kf2-2.jpg","images/seoul/seo-kf2-3.jpg"]},
          {id:"seo-kf3",name:"Gogung Myeongdong (Jeonju bibimbap)",lat:37.5609,lng:126.9855,rating:4.2,price_low:12,price_high:18,blurb:"Traditional Jeonju-style bibimbap in a hot stone bowl, plus jeon and makgeolli. Reliable and tourist-friendly in the heart of Myeongdong.",why:"Best central spot to try proper bibimbap.",place_id:"",images:["images/seoul/seo-kf3-1.jpg","images/seoul/seo-kf3-2.jpg","images/seoul/seo-kf3-3.jpg"]},
          {id:"seo-kf4",name:"Eulji Myeonok (naengmyeon)",lat:37.5660,lng:126.9913,rating:4.3,price_low:10,price_high:16,blurb:"Legendary cold-noodle house in a retro Euljiro building: Pyongyang-style mul-naengmyeon, mung-bean jeon and soju. A summer rite of passage.",why:"The classic Seoul cold-noodle experience.",place_id:"",images:["images/seoul/seo-kf4-1.jpg","images/seoul/seo-kf4-2.jpg","images/seoul/seo-kf4-3.jpg"]},
          {id:"seo-kf5",name:"Jinokhwa Halmae Dakhanmari (Dongdaemun)",lat:37.5703,lng:127.0090,rating:4.2,price_low:18,price_high:28,blurb:"Dakhanmari ('one whole chicken') boiled at your table with leeks and potato, with a soy-mustard dip and a kalguksu-noodle finish. In the Dongdaemun chicken alley.",why:"Communal, warming and very Korean; great for two.",place_id:"",images:["images/seoul/seo-kf5-1.jpg","images/seoul/seo-kf5-2.jpg","images/seoul/seo-kf5-3.jpg"]},
          {id:"seo-kf6",name:"Bossam & Jokbal (Mapo)",lat:37.5493,lng:126.9530,rating:4.4,price_low:18,price_high:35,blurb:"Mapo's cluster of restaurants serve bossam (boiled pork belly wrapped in napa cabbage with fermented shrimp paste) and jokbal (soy-braised pig's trotters). Order a combo platter with soju. The archetypal Korean late-night meal.","why":"Essential Korean eating ritual; Mapo does it best.",images:["images/seoul/seo-kf6-1.jpg","images/seoul/seo-kf6-2.jpg","images/seoul/seo-kf6-3.jpg"]},
          {id:"seo-kf7",name:"Budae Jjigae (Army Stew)",lat:37.5340,lng:126.9942,rating:4.3,price_low:11,price_high:18,blurb:"Korea's beloved post-war comfort stew: kimchi, tofu, ramen noodles, Spam, hot dogs and a slice of cheese cooked together in a gochujang broth at your table. Sharing is mandatory. Abundant near Itaewon and Hongdae.",why:"The most historically fascinating Korean comfort food.",images:["images/seoul/seo-kf7-1.jpg","images/seoul/seo-kf7-2.jpg","images/seoul/seo-kf7-3.jpg"]},
          {id:"seo-kf8",name:"Dakgalbi (Sinchon Spicy Chicken)",lat:37.5551,lng:126.9364,rating:4.4,price_low:12,price_high:20,blurb:"Spicy marinated chicken thigh, rice cakes, cabbage and sweet potato stir-fried on a communal iron plate at the table. Sinchon's Dakgalbi Street has a dozen competing shops. Order the fried rice mixed into the caramelized leftover sauce at the end.",why:"Best budget group meal in Seoul — under $15 per person.",images:["images/seoul/seo-kf8-1.jpg","images/seoul/seo-kf8-2.jpg","images/seoul/seo-kf8-3.jpg"]},
          {id:"seo-kf9",name:"Sundubu Jjigae (Soft Tofu Stew)",lat:37.5600,lng:126.9910,rating:4.4,price_low:9,price_high:16,blurb:"Bubbling stone-pot stew of silken soft tofu in fiery anchovy broth, with a raw egg cracked in at the table. Served with rice and ten small side dishes (banchan). Seoul's best-value complete sit-down meal.",why:"The complete Korean meal for under $12; the perfect lunch.",images:["images/seoul/seo-kf9-1.jpg","images/seoul/seo-kf9-2.jpg","images/seoul/seo-kf9-3.jpg"]},
          {id:"seo-kf10",name:"Gopchang (Grilled Intestines, Euljiro)",lat:37.5620,lng:127.0095,rating:4.3,price_low:20,price_high:35,blurb:"Small and large intestine grilled over charcoal — chewy, fatty and intensely savory. A celebrated Korean delicacy with no close Western analogy. The Euljiro–Dongdaemun alley has specialist gopchang restaurants that fill after 9pm.",why:"The adventurous eater's essential Seoul experience.",images:["images/seoul/seo-kf10-1.jpg","images/seoul/seo-kf10-2.jpg","images/seoul/seo-kf10-3.jpg"]},
          {id:"seo-ir1",name:"Bangkok Recipe (Itaewon, Thai)",lat:37.5356,lng:126.9918,rating:4.3,price_low:15,price_high:25,blurb:"Itaewon most consistently recommended Thai restaurant: green curry, pad see ew and spicy larb at local prices in a bright no-frills room.",why:"Best Thai in Seoul; essential for variety across an 11-night stay."},
          {id:"seo-ir2",name:"Vatos Urban Tacos (Itaewon, Mexican)",lat:37.5348,lng:126.9936,rating:4.4,price_low:15,price_high:25,blurb:"Seoul beloved Korean-Mexican fusion taqueria in Itaewon: kimchi carnitas tacos, galbi quesadillas and frozen margaritas. Loud, packed and fun.",why:"Uniquely Seoul take on Mexican food; great for groups."},
          {id:"seo-ir3",name:"C'ote Korea (Modern Korean, Itaewon)",lat:37.5344,lng:126.9940,rating:4.5,price_low:45,price_high:70,blurb:"Intimate modern Korean tasting-menu restaurant in Itaewon: chef-driven small plates built around seasonal Korean ingredients. No tourist gimmicks.",why:"The mid-splurge option that outpunches its price; pairs with an Itaewon evening."},
          {id:"seo-ins1",name:"Sanchon (Insadong, temple cuisine)",lat:37.5737,lng:126.9869,rating:4.4,price_low:20,price_high:35,blurb:"Insadong legendary Buddhist temple-food restaurant: dozens of seasonal vegetarian dishes served in a fixed multi-course set, all without meat, onion or garlic. The most meditative dining in Seoul.",why:"Completely unique to Korea; pairs with an Insadong cultural day."}
        ],
        street_food: [
          {id:"seo-sf1",name:"Tongin Market Yeopjeon Dosirak Cafe",lat:37.5806,lng:126.9707,rating:4.2,price_low:6,price_high:10,blurb:"Buy brass 'yeopjeon' coins, then fill an old-school lunchbox tray from the market stalls — tteokbokki, jeon, fried bites. Playful, cheap and very local.",why:"Interactive market lunch you won't find elsewhere.",place_id:"",images:["images/seoul/seo-sf1-1.jpg","images/seoul/seo-sf1-2.jpg","images/seoul/seo-sf1-3.jpg"]},
          {id:"seo-sf2",name:"Mukshidonna Tteokbokki (Hongdae)",lat:37.5556,lng:126.9229,rating:4.3,price_low:8,price_high:14,blurb:"Cook-at-your-table 'jeukseok' tteokbokki loaded with ramen, dumplings and cheese, then fry rice in the leftover sauce. Spicy, gooey, student-beloved.",why:"The full tteokbokki ritual, not just a snack.",place_id:"",images:["images/seoul/seo-sf2-1.jpg","images/seoul/seo-sf2-2.jpg","images/seoul/seo-sf2-3.jpg"]},
          {id:"seo-sf3",name:"Namdaemun Market (Kalguksu Alley)",lat:37.5594,lng:126.9776,rating:4.3,price_low:6,price_high:12,blurb:"A 600-year-old market: dive into the famous knife-noodle alley and galchi-stew row, then hotteok and veggie-stuffed pancakes. Grittier and more local than Myeongdong.",why:"Older, rawer market-food crawl.",place_id:"",images:["images/seoul/seo-sf3-1.jpg","images/seoul/seo-sf3-2.jpg","images/seoul/seo-sf3-3.jpg"]},
          {id:"seo-sf4",name:"Sindang Tteokbokki Town",lat:37.5587,lng:127.0097,rating:4.3,price_low:5,price_high:12,blurb:"An entire block of tteokbokki stalls around Sindang Station — the birthplace of the modern gochujang-spiced version. Communal pot dining: chewy rice cakes, fish cakes, ramen noodles and boiled eggs. Add cheese or ramen for a few hundred won extra.",why:"The pilgrimage spot for Korea's defining street food.",images:["images/seoul/seo-sf4-1.jpg","images/seoul/seo-sf4-2.jpg","images/seoul/seo-sf4-3.jpg"]},
          {id:"seo-sf5",name:"Pojangmacha (Tent Street Bars)",lat:37.5250,lng:126.9310,rating:4.3,price_low:6,price_high:18,blurb:"Orange-tented roadside stalls serving odeng (fish cake soup skewers), twigim (fried snacks), tteokbokki and soju by the roadside. The Korean working person's outdoor pub. Clusters near Han River parks, Dongdaemun and Hongdae after dark.",why:"Most authentically local, tourist-free way to eat and drink in Seoul.",images:["images/seoul/seo-sf5-1.jpg","images/seoul/seo-sf5-2.jpg","images/seoul/seo-sf5-3.jpg"]},
          {id:"seo-sf6",name:"Dongdaemun 24h Night Snacks",lat:37.5678,lng:127.0098,rating:4.2,price_low:4,price_high:12,blurb:"The streets around Dongdaemun run all night — vendors sell hotteok (brown-sugar pancakes), gyeran-ppang (egg bread), corn dogs and tteokbokki through to dawn. Best between midnight and 4am when the fashion malls are also open.",why:"Only place in Seoul to eat street food at 3am surrounded by people shopping for clothes.",images:["images/seoul/seo-sf6-1.jpg","images/seoul/seo-sf6-2.jpg","images/seoul/seo-sf6-3.jpg"]},
          {id:"seo-sf7",name:"Egg Drop (Hongdae sandwich chain)",lat:37.5558,lng:126.9228,rating:4.4,price_low:7,price_high:12,blurb:"Seoul viral brioche-egg sandwich chain: butter-braised eggs with avocado, bacon or short-rib on pillowy bread. Constantly long queues in Hongdae from 10am; go early or mid-afternoon.",why:"The most talked-about casual breakfast in Seoul; worth one visit."}
        ],
        fine_dining: [
          {id:"seo-fd1",name:"Mingles (Cheongdam, 3 Michelin)",lat:37.5258,lng:127.0445,rating:4.6,price_low:150,price_high:300,blurb:"Korea's flagship fine-dining room: three-Michelin-star modern Korean by chef Mingoo Kang, famous for the fermented-jang dessert trio. Book weeks ahead.",why:"The splurge-of-the-trip tasting menu.",place_id:"",images:["images/seoul/seo-fd1-1.jpg","images/seoul/seo-fd1-2.jpg","images/seoul/seo-fd1-3.jpg"]},
          {id:"seo-fd2",name:"Jungsik (Gangnam, 2 Michelin)",lat:37.5251,lng:127.0405,rating:4.5,price_low:130,price_high:250,blurb:"Two-Michelin-star 'new Korean' — playful, beautifully plated tasting menus. The original of the NYC/Seoul pair.",why:"Refined modern Korean without the 3-star wait.",place_id:"",images:["images/seoul/seo-fd2-1.jpg","images/seoul/seo-fd2-2.jpg","images/seoul/seo-fd2-3.jpg"]},
          {id:"seo-fd3",name:"Onjium (Seochon hansik)",lat:37.5772,lng:126.9706,rating:4.5,price_low:80,price_high:180,blurb:"Run by a cultural foundation researching royal-court cuisine; elegant seasonal hansik near Gyeongbokgung. One Michelin star.",why:"Most authentic high-end traditional Korean.",place_id:"",images:["images/seoul/seo-fd3-1.jpg","images/seoul/seo-fd3-2.jpg","images/seoul/seo-fd3-3.jpg"]},
          {id:"seo-fd4",name:"La Yeon (The Shilla, 23F)",lat:37.5560,lng:127.0056,rating:4.6,price_low:180,price_high:350,blurb:"Three-Michelin-star Korean fine dining atop The Shilla hotel, with city views, polished service and traditional dishes elevated.",why:"Old-guard luxury hansik with a skyline.",place_id:"",images:["images/seoul/seo-fd4-1.jpg","images/seoul/seo-fd4-2.jpg","images/seoul/seo-fd4-3.jpg"]}
        ],
        museum: [
          {id:"seo-mu1",name:"National Museum of Korea",lat:37.5240,lng:126.9803,rating:4.7,price_low:0,price_high:0,blurb:"One of the world's largest museums — 5,000 years of history, the Silla gold crowns and the Pensive Bodhisattva. Free; the grounds and reflecting pond are gorgeous.",why:"The single best free thing in Seoul.",place_id:"",images:["images/seoul/seo-mu1-1.jpg","images/seoul/seo-mu1-2.jpg","images/seoul/seo-mu1-3.jpg"]},
          {id:"seo-mu2",name:"Leeum Museum of Art (Hannam)",lat:37.5385,lng:126.9990,rating:4.5,price_low:0,price_high:15,blurb:"Samsung's art museum pairs Korean treasures with blue-chip modern (Rothko, Hirst, Lee Ufan) in buildings by Botta, Nouvel and Koolhaas.",why:"Best art museum in the city.",place_id:"",images:["images/seoul/seo-mu2-1.jpg","images/seoul/seo-mu2-2.jpg","images/seoul/seo-mu2-3.jpg"]},
          {id:"seo-mu3",name:"War Memorial of Korea",lat:37.5369,lng:126.9774,rating:4.6,price_low:0,price_high:0,blurb:"A huge, moving museum on the Korean War with outdoor tanks, planes and ships. Free and genuinely impressive regardless of your history.",why:"Free, sobering and memorable.",place_id:"",images:["images/seoul/seo-mu3-1.jpg","images/seoul/seo-mu3-2.jpg","images/seoul/seo-mu3-3.jpg"]},
          {id:"seo-mu4",name:"MMCA Seoul (Samcheong)",lat:37.5786,lng:126.9800,rating:4.4,price_low:0,price_high:4,blurb:"The central branch of the National Museum of Modern & Contemporary Art — strong rotating shows, walkable from the palaces.",why:"Contemporary art between palace visits.",place_id:"",images:["images/seoul/seo-mu4-1.jpg","images/seoul/seo-mu4-2.jpg","images/seoul/seo-mu4-3.jpg"]},
          {id:"seo-mu5",name:"Seoul Museum of Art (SeMA)",lat:37.5640,lng:126.9737,rating:4.4,price_low:0,price_high:0,blurb:"Free city art museum behind a handsome 1928 facade near City Hall; consistently good photography and design exhibitions.",why:"Free, central, quick culture hit.",place_id:"",images:["images/seoul/seo-mu5-1.jpg","images/seoul/seo-mu5-2.jpg","images/seoul/seo-mu5-3.jpg"]}
        ],
        temple: [
          {id:"seo-tp1",name:"Jogyesa Temple (Insadong)",lat:37.5747,lng:126.9817,rating:4.5,price_low:0,price_high:0,blurb:"Head temple of Korean Jogye Buddhism, right downtown — lantern canopies, 500-year-old trees and monks chanting. Free; templestay and tea on offer.",why:"Active city-center temple, no trip required.",place_id:"",images:["images/seoul/seo-tp1-1.jpg","images/seoul/seo-tp1-2.jpg","images/seoul/seo-tp1-3.jpg"]},
          {id:"seo-tp2",name:"Bongeunsa Temple (Gangnam)",lat:37.5150,lng:127.0577,rating:4.6,price_low:0,price_high:0,blurb:"A 1,200-year-old temple facing the COEX towers — a striking old-meets-new view. 23m stone Maitreya; English templestay and tea ceremony.",why:"Best temple-with-skyline photo.",place_id:"",images:["images/seoul/seo-tp2-1.jpg","images/seoul/seo-tp2-2.jpg","images/seoul/seo-tp2-3.jpg"]},
          {id:"seo-tp3",name:"Gilsangsa Temple (Seongbuk)",lat:37.5969,lng:127.0006,rating:4.5,price_low:0,price_high:0,blurb:"A serene wooded temple converted from a former luxury restaurant and donated to Buddhism. Quiet, leafy, almost no tourists.",why:"The peaceful, off-radar alternative.",place_id:"",images:["images/seoul/seo-tp3-1.jpg","images/seoul/seo-tp3-2.jpg","images/seoul/seo-tp3-3.jpg"]}
        ],
        garden: [
          {id:"seo-ga1",name:"Seoul Forest (Seongsu)",lat:37.5444,lng:127.0374,rating:4.4,price_low:0,price_high:0,blurb:"Seoul's 'Central Park' — wetlands, a deer enclosure, riverside paths, and the trendy Seongsu cafes right outside. Rent a bike.",why:"Best big green space + Seongsu cafe crawl.",place_id:"",images:["images/seoul/seo-ga1-1.jpg","images/seoul/seo-ga1-2.jpg","images/seoul/seo-ga1-3.jpg"]},
          {id:"seo-ga2",name:"Olympic Park (Songpa)",lat:37.5202,lng:127.1216,rating:4.5,price_low:0,price_high:0,blurb:"Vast 1988-Games park with the lone 'Tree of Love', a rose garden, a sculpture trail and the Mongchontoseong earthen fortress. Picnic heaven.",why:"Huge, photogenic, great for a slow day.",place_id:"",images:["images/seoul/seo-ga2-1.jpg","images/seoul/seo-ga2-2.jpg","images/seoul/seo-ga2-3.jpg"]},
          {id:"seo-ga3",name:"Seonyudo Park (Han River island)",lat:37.5430,lng:126.8980,rating:4.5,price_low:0,price_high:0,blurb:"A former water-treatment plant on a river island reborn as a moody eco-garden of greenhouses and overgrown concrete, reached by an arched footbridge.",why:"Seoul's most atmospheric, design-y park.",place_id:"",images:["images/seoul/seo-ga3-1.jpg","images/seoul/seo-ga3-2.jpg","images/seoul/seo-ga3-3.jpg"]},
          {id:"seo-ga4",name:"Garden of Morning Calm (Gapyeong, day trip)",lat:37.7430,lng:127.3520,rating:4.5,price_low:8,price_high:12,blurb:"Korea's oldest private garden, in the mountains ~1.5h out; stunning by day and during the light festivals. Combine with Nami Island.",why:"Best day-trip garden; pairs with Nami Island.",place_id:"",images:["images/seoul/seo-ga4-1.jpg","images/seoul/seo-ga4-2.jpg","images/seoul/seo-ga4-3.jpg"]},
          {id:"seo-hng1",name:"Ttukseom Hangang Park",lat:37.5427,lng:127.0668,rating:4.5,price_low:0,price_high:0,blurb:"A long grassy riverfront park near Seongsu with rental bikes, outdoor pools in summer, late-night convenience-store picnic culture and one of the best city skyline views in Seoul.",why:"Closest Hangang park to Seongsu; perfect for an evening after Seoul Forest."}
        ],
        walk: [
          {id:"seo-wk1",name:"Ikseon-dong Hanok Alleys",lat:37.5742,lng:126.9905,rating:4.4,price_low:0,price_high:0,blurb:"1920s hanok lanes turned into a maze of tiny cafes, vintage shops and restaurants — the most charming 'getting-lost' wander in central Seoul.",why:"Prettiest alley-wander and cafe crawl.",place_id:"",images:["images/seoul/seo-wk1-1.jpg","images/seoul/seo-wk1-2.jpg","images/seoul/seo-wk1-3.jpg"]},
          {id:"seo-wk2",name:"Insadong & Ssamzigil",lat:37.5717,lng:126.9856,rating:4.3,price_low:0,price_high:0,blurb:"Traditional-craft main street: tea houses, calligraphy, hanji paper and the spiraling Ssamzigil mall. Touristy, but the souvenir-hunting is real.",why:"One-stop for crafts and tea.",place_id:"",images:["images/seoul/seo-wk2-1.jpg","images/seoul/seo-wk2-2.jpg","images/seoul/seo-wk2-3.jpg"]},
          {id:"seo-wk3",name:"Seoullo 7017 Sky Garden",lat:37.5560,lng:126.9707,rating:4.0,price_low:0,price_high:0,blurb:"An old highway overpass turned elevated garden walk with 200+ plant species, linking Seoul Station to Namdaemun. Best at dusk when it lights up.",why:"Quick, quirky elevated stroll.",place_id:"",images:["images/seoul/seo-wk3-1.jpg","images/seoul/seo-wk3-2.jpg","images/seoul/seo-wk3-3.jpg"]},
          {id:"seo-wk4",name:"Euljiro 'Hipjiro' Backstreets",lat:37.5660,lng:126.9919,rating:4.3,price_low:0,price_high:0,blurb:"Hardware district by day; by night a warren of hidden rooftop bars and retro 'nogari' beer alleys above the print shops. Seoul's coolest contradiction.",why:"Best area for a hip night-walk and drinks.",place_id:"",images:["images/seoul/seo-wk4-1.jpg","images/seoul/seo-wk4-2.jpg","images/seoul/seo-wk4-3.jpg"]},
          {id:"seo-wk5",name:"Garosu-gil (Apgujeong / Sinsa)",lat:37.5196,lng:127.0226,rating:4.5,price_low:0,price_high:0,blurb:"A ginkgo-lined kilometer of boutique fashion, specialty coffee and art galleries in Gangnam — indie Korean brands, concept restaurants and a few Michelin addresses. Stunning in autumn when the trees turn gold.",why:"Seoul's most stylish strolling street; no tourist kitsch.",images:["images/seoul/seo-wk5-1.jpg","images/seoul/seo-wk5-2.jpg","images/seoul/seo-wk5-3.jpg"]},
          {id:"seo-wk6",name:"Seochon Village",lat:37.5795,lng:126.9700,rating:4.4,price_low:0,price_high:0,blurb:"A quiet maze of converted hanok homes wedged between Gyeongbokgung Palace and Inwangsan mountain — indie tea houses, artist galleries, old bookshops and a pace that's vanished from trendier neighborhoods.",why:"More authentic and less crowded than Bukchon; the locals' choice.",images:["images/seoul/seo-wk6-1.jpg","images/seoul/seo-wk6-2.jpg","images/seoul/seo-wk6-3.jpg"]},
          {id:"seo-wk7",name:"Cheonggyecheon Stream (city-center walk)",lat:37.5694,lng:126.9770,rating:4.6,price_low:0,price_high:0,blurb:"A 6 km urban stream restored beneath downtown Seoul, lined with stepping stones, weeping willows and light installations. Start at Cheonggye Plaza near City Hall and walk east toward Dongdaemun. Especially beautiful after dark.",why:"Best free evening stroll in central Seoul.",images:["images/seoul/seo-wk7-1.jpg","images/seoul/seo-wk7-2.jpg","images/seoul/seo-wk7-3.jpg"]},
          {id:"seo-wk8",name:"Hannam-dong Gallery Walk",lat:37.5340,lng:126.9985,rating:4.4,price_low:0,price_high:0,blurb:"Two walkable streets in Hannam-dong cluster world-class galleries (Leeum Samsung Museum, Thaddaeus Ropac Seoul), indie bookshops (What the Book, Seoul Selection) and low-key café-restaurants. No queues, no tourist groups.",why:"Best neighborhood for serious art-browsing combined with coffee.",images:["images/seoul/seo-wk8-1.jpg","images/seoul/seo-wk8-2.jpg","images/seoul/seo-wk8-3.jpg"]}
        ],
        hike: [
          {id:"seo-hk1",name:"Bukhansan National Park (Baegundae)",lat:37.6586,lng:126.9779,rating:4.7,price_low:0,price_high:0,blurb:"A real granite-peak national park inside the city limits. The Baegundae summit (836m) is a chain-assisted scramble with a 360 degree payoff; gentler valley trails too.",why:"World-class hiking 40 min from downtown.",place_id:"",images:["images/seoul/seo-hk1-1.jpg","images/seoul/seo-hk1-2.jpg","images/seoul/seo-hk1-3.jpg"]},
          {id:"seo-hk2",name:"Inwangsan (City Wall + sunset)",lat:37.5790,lng:126.9590,rating:4.6,price_low:0,price_high:0,blurb:"Rocky ridge above the old city with the Seoul City Wall and a shaman shrine, and arguably the best sunset over the palaces and N Tower. About 2 hours.",why:"Best short hike for a skyline sunset.",place_id:"",images:["images/seoul/seo-hk2-1.jpg","images/seoul/seo-hk2-2.jpg","images/seoul/seo-hk2-3.jpg"]},
          {id:"seo-hk3",name:"Achasan (sunrise over the Han)",lat:37.5546,lng:127.1010,rating:4.5,price_low:0,price_high:0,blurb:"Easy, popular eastern ridge with fortress ruins and a wide view of the Han River bends. Locals climb it for sunrise.",why:"Easiest 'real' hike with a big river view.",place_id:"",images:["images/seoul/seo-hk3-1.jpg","images/seoul/seo-hk3-2.jpg","images/seoul/seo-hk3-3.jpg"]},
          {id:"seo-hk4",name:"Ansan Jarak-gil (Bongsudae)",lat:37.5742,lng:126.9430,rating:4.5,price_low:0,price_high:0,blurb:"A gentle wooded mountain with a metasequoia 'sky' boardwalk and a beacon-mound summit facing Inwangsan and the city. Family-easy.",why:"Most relaxed hike; shady in summer.",place_id:"",images:["images/seoul/seo-hk4-1.jpg","images/seoul/seo-hk4-2.jpg","images/seoul/seo-hk4-3.jpg"]}
        ],
        beach: [
          {id:"seo-be1",name:"Eurwangni Beach (near Incheon Airport)",lat:37.4456,lng:126.3736,rating:4.1,price_low:0,price_high:0,blurb:"The closest proper sand-and-sunset beach to Seoul, on the airport island (about 1h). Clam-grill restaurants line the shore; famous west-coast sunsets.",why:"Easiest beach escape; perfect before flying out.",place_id:"",images:["images/seoul/seo-be1-1.jpg","images/seoul/seo-be1-2.jpg","images/seoul/seo-be1-3.jpg"]},
          {id:"seo-be2",name:"Muuido – Hanagae Beach (Incheon)",lat:37.3870,lng:126.4140,rating:4.2,price_low:2,price_high:5,blurb:"A small island beach about 1.5h away with tidal flats, seafood shacks and rustic A-frame huts on the sand. Low-key, scenic, very un-Seoul.",why:"Most scenic nearby island beach.",place_id:"",images:["images/seoul/seo-be2-1.jpg","images/seoul/seo-be2-2.jpg","images/seoul/seo-be2-3.jpg"]}
        ],
        korean_culture: [
          {id:"seo-kc1",name:"Hanbok Rental at Gyeongbokgung",lat:37.5759,lng:126.9740,rating:4.6,price_low:12,price_high:25,blurb:"Rent a hanbok for a few hours by the palace gate (Oneday Hanbok, Hanboknam, etc.) — and palace entry becomes free. The thing to do for old-city photos.",why:"Free palace entry + the iconic Seoul photos.",place_id:"",images:["images/seoul/seo-kc1-1.jpg","images/seoul/seo-kc1-2.jpg","images/seoul/seo-kc1-3.jpg"]},
          {id:"seo-kc2",name:"O'ngo Korean Cooking Class (Insadong)",lat:37.5710,lng:126.9886,rating:4.8,price_low:60,price_high:90,blurb:"Hands-on small-group class — kimchi, bulgogi, tteokbokki — from a long-running English-speaking school that also runs night food tours.",why:"Best-reviewed cooking class; take the recipes home.",place_id:"",images:["images/seoul/seo-kc2-1.jpg","images/seoul/seo-kc2-2.jpg","images/seoul/seo-kc2-3.jpg"]},
          {id:"seo-kc3",name:"Bongeunsa Templestay",lat:37.5150,lng:127.0577,rating:4.7,price_low:50,price_high:80,blurb:"Half-day or overnight templestay in Gangnam: lotus-lantern making, 108 prostrations, a monk tea-talk and temple food. English programs available.",why:"The calm, reflective counterpoint to the city.",place_id:"",images:["images/seoul/seo-kc3-1.jpg","images/seoul/seo-kc3-2.jpg","images/seoul/seo-kc3-3.jpg"]},
          {id:"seo-kc4",name:"1MILLION Dance Studio (K-pop class)",lat:37.5118,lng:127.0590,rating:4.7,price_low:20,price_high:35,blurb:"The world-famous K-pop dance studio; drop-in classes for all levels with choreographers behind major idol videos. Book a beginner GROOVE class.",why:"The most fun only-in-Korea activity.",place_id:"",images:["images/seoul/seo-kc4-1.jpg","images/seoul/seo-kc4-2.jpg","images/seoul/seo-kc4-3.jpg"]}
        ],
        color: [
          {id:"seo-co1",name:"Color Doodle Personal Color (Myeongdong)",lat:37.5637,lng:126.9852,rating:4.7,price_low:60,price_high:110,blurb:"Personal-color studio popular with visitors: a consultant drapes fabrics to find your 'season' and sends you off with a palette card. English service; book ahead.",why:"Most foreigner-friendly color session.",place_id:"",images:["images/seoul/seo-co-generic-1.jpg","images/seoul/seo-co-generic-2.jpg","images/seoul/seo-co-generic-3.jpg"]},
          {id:"seo-co2",name:"OWHITE Personal Color (Hongdae)",lat:37.5556,lng:126.9230,rating:4.8,price_low:70,price_high:130,blurb:"Detailed warm/cool diagnosis plus makeup-shade and jewelry-metal advice; some packages add face-shape analysis.",why:"Most thorough analysis with a full report.",place_id:"",images:["images/seoul/seo-co-generic-1.jpg","images/seoul/seo-co-generic-2.jpg","images/seoul/seo-co-generic-3.jpg"]},
          {id:"seo-co3",name:"Bidam Personal Color (Gangnam)",lat:37.5045,lng:127.0240,rating:4.7,price_low:60,price_high:120,blurb:"Sleek Gangnam studio offering personal color plus face and style consulting; popular right before a shopping day.",why:"Pair it with Gangnam/Myeongdong shopping.",place_id:"",images:["images/seoul/seo-co-generic-1.jpg","images/seoul/seo-co-generic-2.jpg","images/seoul/seo-co-generic-3.jpg"]}
        ],
        skincare: [
          {id:"seo-sk1",name:"Shangpree Spa (Gangnam)",lat:37.5223,lng:127.0290,rating:4.7,price_low:90,price_high:200,blurb:"Award-winning Korean facial spa (the brand behind the cult sheet masks). Signature gold and lifting facials in a serene Gangnam townhouse.",why:"Best dedicated facial experience in Seoul.",place_id:"",images:["images/seoul/seo-sk1-1.jpg","images/seoul/seo-sk1-2.jpg","images/seoul/seo-sk1-3.jpg"]},
          {id:"seo-sk2",name:"Sulwhasoo Spa (Bukchon Flagship)",lat:37.5410,lng:127.0390,rating:4.6,price_low:120,price_high:300,blurb:"Luxury hanbang (herbal) facial spa from Korea's heritage skincare house, in a striking flagship. Ginseng-based treatments; pure indulgence.",why:"The high-end traditional-ingredient splurge.",place_id:"",images:["images/seoul/seo-sk2-1.jpg","images/seoul/seo-sk2-2.jpg","images/seoul/seo-sk2-3.jpg"]},
          {id:"seo-sk3",name:"Spa Lei (women-only, Gangnam)",lat:37.5040,lng:127.0250,rating:4.3,price_low:12,price_high:25,blurb:"Upscale women-only Korean spa: hot/cold pools, a seshin body scrub and sauna rooms — the affordable 'glass-skin' ritual locals actually use.",why:"Everyday-Korean skincare ritual (women only).",place_id:"",images:["images/seoul/seo-sk3-1.jpg","images/seoul/seo-sk3-2.jpg","images/seoul/seo-sk3-3.jpg"]},
          {id:"seo-sk4",name:"Dragon Hill Spa (Yongsan, 24h jjimjilbang)",lat:37.5272,lng:126.9640,rating:4.2,price_low:12,price_high:22,blurb:"Korea's most-visited 24h jjimjilbang: seven floors of hot/cold pools, loofah scrub rooms, saunas, sleeping areas, a rooftop pool and a food court — all included in the ~₩15,000 ($12) entry fee. English signage throughout. Men and women both welcome.",why:"The iconic Korean public spa at a fraction of hotel prices.",place_id:"",images:["images/seoul/seo-sk4-1.jpg","images/seoul/seo-sk4-2.jpg","images/seoul/seo-sk4-3.jpg"]}
        ],
        club: [
          {id:"seo-nc1",name:"Octagon (Gangnam)",lat:37.5045,lng:127.0238,rating:4.3,price_low:30,price_high:50,blurb:"Multi-floor Gangnam mega-club regularly ranked among the world's top 10 — big-room EDM, huge sound, serious queues. Dress up.",why:"The blockbuster Seoul club night.",place_id:"",images:["images/seoul/seo-nc1-1.jpg","images/seoul/seo-nc1-2.jpg","images/seoul/seo-nc1-3.jpg"]},
          {id:"seo-nc2",name:"Cakeshop (Itaewon)",lat:37.5345,lng:126.9945,rating:4.4,price_low:20,price_high:35,blurb:"Small, influential basement club for hip-hop, house and touring underground DJs — where Seoul's music heads actually go.",why:"Best credible underground night.",place_id:"",images:["images/seoul/seo-nc2-1.jpg","images/seoul/seo-nc2-2.jpg","images/seoul/seo-nc2-3.jpg"]},
          {id:"seo-nc3",name:"Soap Seoul (Gangnam)",lat:37.5075,lng:127.0205,rating:4.2,price_low:25,price_high:45,blurb:"Stylish Gangnam club known for house and techno bookings and a less bottle-service-y floor than its neighbours.",why:"Gangnam clubbing without the table scene.",place_id:"",images:["images/seoul/seo-nc3-1.jpg","images/seoul/seo-nc3-2.jpg","images/seoul/seo-nc3-3.jpg"]},
          {id:"seo-nc4",name:"NB2 (Hongdae)",lat:37.5555,lng:126.9235,rating:4.1,price_low:15,price_high:25,blurb:"YG-affiliated hip-hop club in the heart of Hongdae — cheap entry, young crowd, K-hip-hop and R&B until dawn.",why:"Cheapest, most energetic Hongdae night.",place_id:"",images:["images/seoul/seo-nc4-1.jpg","images/seoul/seo-nc4-2.jpg","images/seoul/seo-nc4-3.jpg"]},
          {id:"seo-nc5",name:"Venue (Itaewon, underground)",lat:37.5343,lng:126.9944,rating:4.2,price_low:12,price_high:22,blurb:"Veteran Itaewon underground club in a basement labyrinth: multiple rooms playing techno, drum & bass and experimental dance music. Smaller and rawer than Octagon — resident DJ culture, loyal regular crowd.",why:"Best underground electronic club in Seoul; no bottle-service floor.",images:["images/seoul/seo-nc5-1.jpg","images/seoul/seo-nc5-2.jpg","images/seoul/seo-nc5-3.jpg"]},
          {id:"seo-nc6",name:"Club Made (Itaewon, hip-hop & R&B)",lat:37.5344,lng:126.9940,rating:4.1,price_low:12,price_high:22,blurb:"Long-running Itaewon hip-hop and R&B club with a diverse Korean and international crowd. Consistent music policy, relaxed door and the most approachable hip-hop night in the city.",why:"Best hip-hop club for a mixed crowd; easier door than Cakeshop.",images:["images/seoul/seo-nc6-1.jpg","images/seoul/seo-nc6-2.jpg","images/seoul/seo-nc6-3.jpg"]},
          {id:"seo-nc7",name:"Eden Club (Gangnam)",lat:37.5068,lng:127.0240,rating:4.0,price_low:22,price_high:45,blurb:"Gangnam mega-club with two main rooms and a rooftop terrace — EDM and hip-hop nights, serious light production and VIP table sections. Dress code enforced. Slightly more accessible than Octagon on weeknights.",why:"Alternative to Octagon; same Gangnam energy, slightly easier to get into.",images:["images/seoul/seo-nc7-1.jpg","images/seoul/seo-nc7-2.jpg","images/seoul/seo-nc7-3.jpg"]},
          {id:"seo-hb2",name:"Club FF (Hongdae)",lat:37.5520,lng:126.9228,rating:4.2,price_low:10,price_high:20,blurb:"Long-running Hongdae club on two floors: K-pop and hip-hop upstairs, harder electronic music in the basement. Cheap entry, young local crowd, open until 5am.",why:"Classic Hongdae club; cheaper and more local than Gangnam options."},
          {id:"seo-hb3",name:"FREEBIRD (Hongdae)",lat:37.5525,lng:126.9222,rating:4.2,price_low:10,price_high:18,blurb:"A Hongdae club with a party-festival energy: body paint events, themed nights and a roster of local DJs. More experimental and fun than the mainstream K-pop clubs nearby.",why:"The Hongdae alternative club night; better music variety."}
        ],
        casino: [
          {id:"seo-ca1",name:"Paradise City (near Incheon Airport)",lat:37.4290,lng:126.4530,rating:4.3,price_low:0,price_high:50,blurb:"Korea's first integrated casino-resort by the airport: a foreigners-only casino, art everywhere (Koons, Kusama), a club, spa and hotel. Great last night before flying.",why:"Full Vegas-style resort on the way out.",place_id:"",images:["images/seoul/seo-ca1-1.jpg","images/seoul/seo-ca1-2.jpg","images/seoul/seo-ca1-3.jpg"]},
          {id:"seo-ca2",name:"Seven Luck Casino (COEX, Gangnam)",lat:37.5118,lng:127.0590,rating:4.0,price_low:0,price_high:50,blurb:"Central foreigners-only casino at COEX — tables and slots, open 24h, easy to drop into after dinner. Bring your passport.",why:"Most convenient in-city casino.",place_id:"",images:["images/seoul/seo-ca2-1.jpg","images/seoul/seo-ca2-2.jpg","images/seoul/seo-ca2-3.jpg"]},
          {id:"seo-ca3",name:"Walkerhill Casino (Gwangnaru)",lat:37.5556,lng:127.1110,rating:4.0,price_low:0,price_high:50,blurb:"The original Seoul foreigners' casino, on a hillside at the Vista Walkerhill with river views and a resort feel.",why:"Resort-style casino with the best setting.",place_id:"",images:["images/seoul/seo-ca3-1.jpg","images/seoul/seo-ca3-2.jpg","images/seoul/seo-ca3-3.jpg"]}
        ],
        stationery: [
          {id:"seo-st1",name:"Artbox Hongdae Flagship",lat:37.5570,lng:126.9263,rating:4.5,price_low:3,price_high:30,blurb:"Korea's biggest stationery and lifestyle chain in its best location — five Hongdae floors of notebooks, sticker sets, phone cases, mugs and seasonal K-character collabs. Easily an hour of browsing.",why:"The definitive Korean stationery haul.",images:["images/seoul/seo-st1-1.jpg","images/seoul/seo-st1-2.jpg","images/seoul/seo-st1-3.jpg"]},
          {id:"seo-st2",name:"Kyobo Book Centre (Gwanghwamun)",lat:37.5700,lng:126.9760,rating:4.6,price_low:5,price_high:40,blurb:"Korea's largest bookstore, underground at Gwanghwamun Square — floor-to-ceiling shelves, a serious English section, a beautiful stationery and fountain-pen floor, and a café. One of the world's great bookshops.",why:"Best bookshop in Seoul; extraordinary stationery selection alongside.",images:["images/seoul/seo-st2-1.jpg","images/seoul/seo-st2-2.jpg","images/seoul/seo-st2-3.jpg"]},
          {id:"seo-st3",name:"10x10 (Hongdae / Myeongdong)",lat:37.5559,lng:126.9238,rating:4.4,price_low:3,price_high:30,blurb:"Trendy Korean lifestyle-and-stationery chain: design-brand notebooks, planner accessories, desktop organizers and quirky gifts. A step more grown-up and design-focused than Artbox.",why:"Complementary to Artbox — different brands, slightly more refined aesthetic.",images:["images/seoul/seo-st3-1.jpg","images/seoul/seo-st3-2.jpg","images/seoul/seo-st3-3.jpg"]},
          {id:"seo-st4",name:"Whalehouse (고래책방, Mangwon)",lat:37.5555,lng:126.9085,rating:4.5,price_low:5,price_high:20,blurb:"Beloved indie bookshop-café in Mangwon with floor-to-ceiling shelves, literary stationery and a warm reading-room atmosphere. Small, quiet and genuinely loved by Seoul's book community.",why:"Best indie bookshop for a slow afternoon away from the crowds.",images:["images/seoul/seo-st4-1.jpg","images/seoul/seo-st4-2.jpg","images/seoul/seo-st4-3.jpg"]}
        ],
        gifts: [
          {id:"seo-gi1",name:"Kakao Friends Flagship (Hongdae)",lat:37.5574,lng:126.9248,rating:4.7,price_low:5,price_high:60,blurb:"Four-floor flagship for the Kakao character universe — Ryan, Apeach and friends in every form: plush toys, stationery, cosmetics, phone cases and seasonal collaborations. Photo zones on every level.",why:"The definitive Korean character-goods experience; excellent for gifts.",images:["images/seoul/seo-gi1-1.jpg","images/seoul/seo-gi1-2.jpg","images/seoul/seo-gi1-3.jpg"]},
          {id:"seo-gi2",name:"Olive Young (Myeongdong Flagship)",lat:37.5623,lng:126.9840,rating:4.6,price_low:8,price_high:80,blurb:"Korea's largest beauty multi-brand chain — sheet masks, sunscreen sticks, toner pads, lip tints, snail serums and more. Three Myeongdong floors at prices 30–50% cheaper than airport duty-free.",why:"Best and cheapest place to buy K-beauty gifts in Seoul.",images:["images/seoul/seo-gi2-1.jpg","images/seoul/seo-gi2-2.jpg","images/seoul/seo-gi2-3.jpg"]},
          {id:"seo-gi3",name:"Insadong Traditional Craft Shops",lat:37.5743,lng:126.9849,rating:4.4,price_low:5,price_high:100,blurb:"Insadong's main street and the Ssamziegil complex concentrate the best traditional craft shops — hanji paper goods, celadon ceramics, lacquerware, ginseng products, woodblock-printed textiles and handmade goods from regional artisans.",why:"Only neighborhood in Seoul entirely dedicated to authentic Korean cultural gifts.",images:["images/seoul/seo-gi3-1.jpg","images/seoul/seo-gi3-2.jpg","images/seoul/seo-gi3-3.jpg"]},
          {id:"seo-gi4",name:"BT21 / Line Friends (Sinchon)",lat:37.5555,lng:126.9356,rating:4.4,price_low:10,price_high:80,blurb:"Line Friends stores carrying BT21 — the BTS-designed character line — in Sinchon and other locations. Every character-branded item imaginable, plus BTS and K-pop collaboration products.",why:"Best for K-pop-adjacent merch and BT21 goods.",images:["images/seoul/seo-gi4-1.jpg","images/seoul/seo-gi4-2.jpg","images/seoul/seo-gi4-3.jpg"]},
          {id:"seo-oy1",name:"Innisfree Myeongdong Flagship",lat:37.5623,lng:126.9843,rating:4.4,price_low:8,price_high:60,blurb:"Jeju-sourced Korean beauty brand across three Myeongdong floors: green tea serums, volcanic clay masks and SPF products at roughly half the airport price. Full range including discontinued favourites.",why:"Best-value Innisfree in Korea; worth a dedicated stop on K-beauty day."},
          {id:"seo-oy2",name:"Tony Moly Myeongdong",lat:37.5628,lng:126.9852,rating:4.3,price_low:5,price_high:40,blurb:"Fun character-driven K-beauty brand with the best gift packaging on the street: panda eye masks, mushroom highlighters and peach-shaped hand creams. Regular buy-two-get-one deals.",why:"Best for gift-buying; the character packaging travels well."}
        ],
        fashion: [
          {id:"seo-fa1",name:"Dongdaemun Fashion Town (24h)",lat:37.5675,lng:127.0100,rating:4.3,price_low:10,price_high:100,blurb:"Seoul's legendary 24-hour fashion district: wholesale malls (Doota, Migliore) stocking K-fashion, streetwear and basics at near-wholesale prices. Fashion floors run 7pm–6am; bring cash and bargaining energy.",why:"Largest single-area fashion shopping in Asia; the only truly all-night option.",images:["images/seoul/seo-fa1-1.jpg","images/seoul/seo-fa1-2.jpg","images/seoul/seo-fa1-3.jpg"]},
          {id:"seo-fa2",name:"Stylenanda / 3CE (Myeongdong Flagship)",lat:37.5633,lng:126.9855,rating:4.6,price_low:25,price_high:120,blurb:"Seven-floor Myeongdong flagship of Korea's cult streetwear and makeup brand — clothing on the lower floors, 3CE cosmetics up top, and a rooftop café with views over the street below. The building is an attraction in itself.",why:"The most Instagram-worthy K-fashion flagship; 3CE makeup is genuinely excellent.",images:["images/seoul/seo-fa2-1.jpg","images/seoul/seo-fa2-2.jpg","images/seoul/seo-fa2-3.jpg"]},
          {id:"seo-fa3",name:"Gentle Monster Apgujeong (Flagship)",lat:37.5278,lng:127.0408,rating:4.7,price_low:200,price_high:450,blurb:"Korea's globally-acclaimed eyewear brand runs its flagship as a rotating art installation — alien sculptures, mechanical creatures and abstract environments change every season. Worth visiting even if you don't buy sunglasses.",why:"The most architecturally extraordinary retail space in Seoul.",images:["images/seoul/seo-fa3-1.jpg","images/seoul/seo-fa3-2.jpg","images/seoul/seo-fa3-3.jpg"]},
          {id:"seo-fa4",name:"Ader Error Flagship (Seongsu)",lat:37.5442,lng:127.0563,rating:4.5,price_low:100,price_high:350,blurb:"Seoul's most internationally recognized streetwear label, with a gallery-store hybrid in the trendy Seongsu district — experimental designs, premium-weight fabrics and ongoing artist collaborations.",why:"The one Korean designer brand serious streetwear buyers should actually shop.",images:["images/seoul/seo-fa4-1.jpg","images/seoul/seo-fa4-2.jpg","images/seoul/seo-fa4-3.jpg"]},
          {id:"seo-fa5",name:"Hongdae Vintage Strip",lat:37.5560,lng:126.9240,rating:4.3,price_low:10,price_high:80,blurb:"A cluster of vintage, deadstock and indie clothing shops concentrated around Hongdae Station — Y2K pieces, 90s sports gear, military surplus, Japanese brands and Korean indie designers. Best on weekend afternoons.",why:"Most concentrated and fun vintage shopping in Seoul.",images:["images/seoul/seo-fa5-1.jpg","images/seoul/seo-fa5-2.jpg","images/seoul/seo-fa5-3.jpg"]},
          {id:"seo-sc2",name:"LCDC Seoul (Seongsu concept complex)",lat:37.5443,lng:127.0548,rating:4.5,price_low:0,price_high:20,blurb:"A six-building converted factory complex in Seongsu housing fashion concept stores, galleries, food brands and pop-up spaces. Seoul answer to Brooklyn cultural-industrial districts.",why:"Best destination for concept-store browsing and gallery-hopping in Seongsu."}
        ],
        makgeolli: [
          {id:"seo-mk1",name:"Insadong Makgeolli Tavern",lat:37.5745,lng:126.9860,rating:4.4,price_low:8,price_high:25,blurb:"Traditional makgeolli bars line the alleys off Insadong — sit on wooden floors in a hanok, order unfiltered rice wine by the bowl and pair it with bindaetteok (mung bean pancake) or pajeon (green onion pancake). The classic Korean rainy-day ritual.",why:"Most atmospheric place to drink makgeolli in Seoul.",images:["images/seoul/seo-mk1-1.jpg","images/seoul/seo-mk1-2.jpg","images/seoul/seo-mk1-3.jpg"]},
          {id:"seo-mk2",name:"Craft Makgeolli Bar (Mapo / Hongdae area)",lat:37.5524,lng:126.9214,rating:4.3,price_low:10,price_high:28,blurb:"Contemporary bars near Hongdae serve small-batch artisan makgeolli flights — sweet, dry, carbonated and grain-forward styles from local breweries. A different world from the mass-market Lotte version. English-friendly.",why:"Best introduction to craft makgeolli beyond mass-market bottles.",images:["images/seoul/seo-mk2-1.jpg","images/seoul/seo-mk2-2.jpg","images/seoul/seo-mk2-3.jpg"]},
          {id:"seo-mk3",name:"Han River Pojangmacha (Yeouido / Banpo)",lat:37.5203,lng:126.9271,rating:4.3,price_low:6,price_high:15,blurb:"Tent-bar rows lining Han River parks at night — soju, makgeolli, instant ramen and fried chicken eaten on plastic stools with river and city views. The quintessential Korean nighttime social ritual.",why:"The most universally loved Korean evening-out experience.",images:["images/seoul/seo-mk3-1.jpg","images/seoul/seo-mk3-2.jpg","images/seoul/seo-mk3-3.jpg"]},
          {id:"seo-chm2",name:"Jindalae Makgeolli (Gangnam)",lat:37.5040,lng:127.0245,rating:4.4,price_low:12,price_high:22,blurb:"A modern makgeolli bar in Gangnam with a refined craft-takju concept: house-brewed rice wines paired with elevated Korean bar food including upgraded pajeon and house bossam.",why:"Best makgeolli bar for pairing with a Gangnam evening."}
        ]
      }
    }
  }
};

if (typeof module !== 'undefined') module.exports = TRIP_DATA;
